import StrategyInnovation.Optimization.CapacityValue

/-!
# Exact capacity complementarity counterexample

Two unit-cost carriers supply different capabilities.  Productive value is
one exactly when both capabilities are retained, and zero otherwise.  The
resulting exact capacity profile is `(0, 0, 1)` at capacities `(0, 1, 2)`, so
the second unit has strictly larger marginal value than the first.
-/

namespace StrategyInnovation

namespace Optimization

namespace CapacityComplementarityCounterexample

/-- The two capabilities jointly required by the productive opportunity. -/
inductive Capability
  | first
  | second
  deriving DecidableEq, Fintype

/-- The four inactive-containing libraries generated by two carriers. -/
inductive Library
  | inactive
  | firstCarrier
  | secondCarrier
  | bothCarriers
  deriving DecidableEq, Fintype

/-- Capabilities carried by each of the four libraries. -/
def carriedCapabilities : Library → Finset Capability
  | .inactive => ∅
  | .firstCarrier => {.first}
  | .secondCarrier => {.second}
  | .bothCarriers => {.first, .second}

/-- The productive opportunity requires both capabilities. -/
def requiredCapabilities : Finset Capability :=
  {.first, .second}

/-- Both active carriers have unit resource burden. -/
def burden : Library → ℝ
  | .inactive => 0
  | .firstCarrier => 1
  | .secondCarrier => 1
  | .bothCarriers => 2

/-- Productive value is generated only by the jointly sufficient pair. -/
def productiveValue : Library → ℝ
  | .inactive => 0
  | .firstCarrier => 0
  | .secondCarrier => 0
  | .bothCarriers => 1

/-- The value table is exactly the indicator of the joint requirement. -/
theorem productiveValue_eq_jointRequirement (library : Library) :
    productiveValue library =
      if requiredCapabilities ⊆ carriedCapabilities library then 1 else 0 := by
  cases library <;>
    simp [productiveValue, requiredCapabilities, carriedCapabilities,
      Finset.ext_iff] <;>
    decide

/-- The fixed finite capacity problem induced by the two carriers. -/
def problem : FiniteCapacityProblem Library where
  feasibleLibraries := Finset.univ
  feasibleLibraries_nonempty := ⟨.inactive, Finset.mem_univ _⟩
  productiveValue := productiveValue
  burden := burden
  burden_nonnegative := by
    intro library _
    cases library <;> norm_num [burden]
  inactiveLibrary := .inactive
  inactive_mem := Finset.mem_univ _
  inactive_burden_zero := rfl

/-- The inactive library is optimal at capacity zero. -/
theorem inactive_isCapacityOptimizer_at_zero :
    problem.IsCapacityOptimizer 0 .inactive := by
  apply problem.isCapacityOptimizer_of_dominates
  · rw [problem.mem_capacityFeasibleLibraries_iff]
    simp [problem, burden]
  · intro competitor hcompetitor
    rw [problem.mem_capacityFeasibleLibraries_iff] at hcompetitor
    rcases hcompetitor with ⟨_, hburden⟩
    cases competitor with
    | inactive => norm_num [problem, productiveValue]
    | firstCarrier => norm_num [problem, burden] at hburden
    | secondCarrier => norm_num [problem, burden] at hburden
    | bothCarriers => norm_num [problem, burden] at hburden

/-- A single resource unit still leaves productive value at zero. -/
theorem inactive_isCapacityOptimizer_at_one :
    problem.IsCapacityOptimizer 1 .inactive := by
  apply problem.isCapacityOptimizer_of_dominates
  · rw [problem.mem_capacityFeasibleLibraries_iff]
    simp [problem, burden]
  · intro competitor hcompetitor
    rw [problem.mem_capacityFeasibleLibraries_iff] at hcompetitor
    rcases hcompetitor with ⟨_, hburden⟩
    cases competitor with
    | inactive => norm_num [problem, productiveValue]
    | firstCarrier => norm_num [problem, productiveValue]
    | secondCarrier => norm_num [problem, productiveValue]
    | bothCarriers => norm_num [problem, burden] at hburden

/-- With two resource units, the jointly sufficient library is optimal. -/
theorem bothCarriers_isCapacityOptimizer_at_two :
    problem.IsCapacityOptimizer 2 .bothCarriers := by
  apply problem.isCapacityOptimizer_of_dominates
  · rw [problem.mem_capacityFeasibleLibraries_iff]
    simp [problem, burden]
  · intro competitor hcompetitor
    rw [problem.mem_capacityFeasibleLibraries_iff] at hcompetitor
    rcases hcompetitor with ⟨_, hburden⟩
    cases competitor <;>
      norm_num [problem, burden, productiveValue] at hburden ⊢

/-- First exact point of the capacity profile: `V⋆(0) = 0`. -/
theorem capacityValue_zero :
    problem.capacityValue 0 = 0 := by
  simpa [problem, productiveValue] using
    inactive_isCapacityOptimizer_at_zero.2.symm

/-- Second exact point of the capacity profile: `V⋆(1) = 0`. -/
theorem capacityValue_one :
    problem.capacityValue 1 = 0 := by
  simpa [problem, productiveValue] using
    inactive_isCapacityOptimizer_at_one.2.symm

/-- Third exact point of the capacity profile: `V⋆(2) = 1`. -/
theorem capacityValue_two :
    problem.capacityValue 2 = 1 := by
  simpa [problem, productiveValue] using
    bothCarriers_isCapacityOptimizer_at_two.2.symm

/-- The first unit has exact shadow value zero. -/
theorem first_unit_shadow_zero :
    problem.discreteShadowValue 0 1 = 0 := by
  simp [FiniteCapacityProblem.discreteShadowValue,
    capacityValue_zero, capacityValue_one]

/-- The second unit has exact shadow value one. -/
theorem second_unit_shadow_one :
    problem.discreteShadowValue 1 1 = 1 := by
  norm_num [FiniteCapacityProblem.discreteShadowValue,
    capacityValue_one, capacityValue_two]

/-- Joint capability requirements produce a strictly increasing marginal. -/
theorem increasing_marginal_capacity_value :
    problem.discreteShadowValue 0 1 <
      problem.discreteShadowValue 1 1 := by
  rw [first_unit_shadow_zero, second_unit_shadow_one]
  norm_num

/-- Discrete diminishing capacity returns therefore fail in the general model. -/
theorem diminishing_capacity_returns_fail :
    ¬ problem.HasDiminishingDiscreteCapacityReturns 1 := by
  intro hdiminishing
  exact (not_lt_of_ge (hdiminishing.2 0 (by norm_num)))
    (by simpa only [zero_add] using increasing_marginal_capacity_value)

end CapacityComplementarityCounterexample

end Optimization

end StrategyInnovation
