import StrategyInnovation.Optimization.CapacityCounterexample
import StrategyInnovation.Optimization.CapacityDiminishingReturns

/-!
# Finite capacity-value audit

This focused gate records the kernel dependencies of CAP, its exact
joint-capability increasing-marginal witness, and the separately scoped
additive equal-unit grid sufficient condition.
-/

#print axioms StrategyInnovation.Optimization.FiniteCapacityProblem
#print axioms StrategyInnovation.Optimization.FiniteCapacityProblem.ofRational
#print axioms StrategyInnovation.Optimization.FiniteCapacityProblem.capacityFeasibleLibraries
#print axioms StrategyInnovation.Optimization.FiniteCapacityProblem.mem_capacityFeasibleLibraries_iff
#print axioms StrategyInnovation.Optimization.FiniteCapacityProblem.inactive_mem_capacityFeasibleLibraries
#print axioms StrategyInnovation.Optimization.FiniteCapacityProblem.capacityFeasibleLibraries_nonempty
#print axioms StrategyInnovation.Optimization.FiniteCapacityProblem.capacityValue
#print axioms StrategyInnovation.Optimization.FiniteCapacityProblem.IsCapacityOptimizer
#print axioms StrategyInnovation.Optimization.FiniteCapacityProblem.capacityOptimizerSet
#print axioms StrategyInnovation.Optimization.FiniteCapacityProblem.capacityValue_eq_sup'_of_nonempty
#print axioms StrategyInnovation.Optimization.FiniteCapacityProblem.productiveValue_le_capacityValue
#print axioms StrategyInnovation.Optimization.FiniteCapacityProblem.isCapacityOptimizer_of_dominates
#print axioms StrategyInnovation.Optimization.FiniteCapacityProblem.exists_capacityOptimizer_of_inactive_feasible
#print axioms StrategyInnovation.Optimization.FiniteCapacityProblem.exists_capacityOptimizer
#print axioms StrategyInnovation.Optimization.FiniteCapacityProblem.capacityOptimizerSet_nonempty
#print axioms StrategyInnovation.Optimization.FiniteCapacityProblem.capacityValue_is_finite_maximum
#print axioms StrategyInnovation.Optimization.FiniteCapacityProblem.capacityFeasibleLibraries_mono
#print axioms StrategyInnovation.Optimization.FiniteCapacityProblem.capacityValue_mono
#print axioms StrategyInnovation.Optimization.FiniteCapacityProblem.attainableBurdens
#print axioms StrategyInnovation.Optimization.FiniteCapacityProblem.burden_mem_attainableBurdens
#print axioms StrategyInnovation.Optimization.FiniteCapacityProblem.zero_mem_attainableBurdens
#print axioms StrategyInnovation.Optimization.FiniteCapacityProblem.attainableBurdenSet_finite
#print axioms StrategyInnovation.Optimization.FiniteCapacityProblem.capacityFeasibleLibraries_eq_of_no_attainableBurden
#print axioms StrategyInnovation.Optimization.FiniteCapacityProblem.capacityValue_eq_of_no_attainableBurden
#print axioms StrategyInnovation.Optimization.FiniteCapacityProblem.AreConsecutiveAttainableBurdens
#print axioms StrategyInnovation.Optimization.FiniteCapacityProblem.capacityValue_constant_between_attainableBurdens
#print axioms StrategyInnovation.Optimization.FiniteCapacityProblem.IsLocallyConstantAt
#print axioms StrategyInnovation.Optimization.FiniteCapacityProblem.capacityBreakpointSet
#print axioms StrategyInnovation.Optimization.FiniteCapacityProblem.eventually_capacityFeasibleLibraries_eq_of_not_attainable
#print axioms StrategyInnovation.Optimization.FiniteCapacityProblem.isLocallyConstantAt_of_not_mem_attainableBurdens
#print axioms StrategyInnovation.Optimization.FiniteCapacityProblem.capacityBreakpointSet_subset_attainableBurdens
#print axioms StrategyInnovation.Optimization.FiniteCapacityProblem.capacityBreakpointSet_finite
#print axioms StrategyInnovation.Optimization.FiniteCapacityProblem.discreteShadowValue
#print axioms StrategyInnovation.Optimization.FiniteCapacityProblem.discreteShadowValue_nonnegative
#print axioms StrategyInnovation.Optimization.FiniteCapacityProblem.HasDiminishingDiscreteCapacityReturns

#print axioms StrategyInnovation.Optimization.CapacityComplementarityCounterexample.productiveValue_eq_jointRequirement
#print axioms StrategyInnovation.Optimization.CapacityComplementarityCounterexample.problem
#print axioms StrategyInnovation.Optimization.CapacityComplementarityCounterexample.inactive_isCapacityOptimizer_at_zero
#print axioms StrategyInnovation.Optimization.CapacityComplementarityCounterexample.inactive_isCapacityOptimizer_at_one
#print axioms StrategyInnovation.Optimization.CapacityComplementarityCounterexample.bothCarriers_isCapacityOptimizer_at_two
#print axioms StrategyInnovation.Optimization.CapacityComplementarityCounterexample.capacityValue_zero
#print axioms StrategyInnovation.Optimization.CapacityComplementarityCounterexample.capacityValue_one
#print axioms StrategyInnovation.Optimization.CapacityComplementarityCounterexample.capacityValue_two
#print axioms StrategyInnovation.Optimization.CapacityComplementarityCounterexample.first_unit_shadow_zero
#print axioms StrategyInnovation.Optimization.CapacityComplementarityCounterexample.second_unit_shadow_one
#print axioms StrategyInnovation.Optimization.CapacityComplementarityCounterexample.increasing_marginal_capacity_value
#print axioms StrategyInnovation.Optimization.CapacityComplementarityCounterexample.diminishing_capacity_returns_fail

#print axioms StrategyInnovation.Optimization.AdditiveUnitCapacityProfile
#print axioms StrategyInnovation.Optimization.AdditiveUnitCapacityProfile.gridCapacity
#print axioms StrategyInnovation.Optimization.AdditiveUnitCapacityProfile.gridCapacity_succ
#print axioms StrategyInnovation.Optimization.AdditiveUnitCapacityProfile.gridValue
#print axioms StrategyInnovation.Optimization.AdditiveUnitCapacityProfile.gridShadow
#print axioms StrategyInnovation.Optimization.AdditiveUnitCapacityProfile.nextIncrement
#print axioms StrategyInnovation.Optimization.AdditiveUnitCapacityProfile.nextIncrement_nonnegative
#print axioms StrategyInnovation.Optimization.AdditiveUnitCapacityProfile.gridShadow_eq_nextIncrement
#print axioms StrategyInnovation.Optimization.AdditiveUnitCapacityProfile.nextIncrement_succ_le
#print axioms StrategyInnovation.Optimization.AdditiveUnitCapacityProfile.gridShadow_antitone
#print axioms StrategyInnovation.Optimization.AdditiveUnitCapacityProfile.gridShadow_succ_le

#lint- only checkType unusedArguments simpNF in StrategyInnovation.Optimization.FiniteCapacityProblem
#lint- only checkType unusedArguments simpNF in StrategyInnovation.Optimization.CapacityComplementarityCounterexample
#lint- only checkType unusedArguments simpNF in StrategyInnovation.Optimization.AdditiveUnitCapacityProfile
