import StrategyInnovation.Optimization.PenalizedEnvelope

/-!
# Finite penalized-envelope audit

This focused gate records the kernel dependencies of the fixed finite-family
real-price envelope, its finite switching candidates, local affine slope, and
set-valued optimal-burden order.
-/

#print axioms StrategyInnovation.Optimization.FinitePenalizedProblem
#print axioms StrategyInnovation.Optimization.FinitePenalizedProblem.ofRational
#print axioms StrategyInnovation.Optimization.FinitePenalizedProblem.ofRational_branch
#print axioms StrategyInnovation.Optimization.FinitePenalizedProblem.branch
#print axioms StrategyInnovation.Optimization.FinitePenalizedProblem.envelope
#print axioms StrategyInnovation.Optimization.FinitePenalizedProblem.IsOptimizer
#print axioms StrategyInnovation.Optimization.FinitePenalizedProblem.optimizerSet
#print axioms StrategyInnovation.Optimization.FinitePenalizedProblem.envelope_is_finite_maximum
#print axioms StrategyInnovation.Optimization.FinitePenalizedProblem.optimizerSet_nonempty
#print axioms StrategyInnovation.Optimization.FinitePenalizedProblem.envelope_antitone
#print axioms StrategyInnovation.Optimization.FinitePenalizedProblem.envelope_convex
#print axioms StrategyInnovation.Optimization.FinitePenalizedProblem.continuous_envelope
#print axioms StrategyInnovation.Optimization.FinitePenalizedProblem.switchingPrice
#print axioms StrategyInnovation.Optimization.FinitePenalizedProblem.pairwiseSwitchingPrices
#print axioms StrategyInnovation.Optimization.FinitePenalizedProblem.pairwiseSwitchingPriceSet_finite
#print axioms StrategyInnovation.Optimization.FinitePenalizedProblem.branch_eq_at_switchingPrice
#print axioms StrategyInnovation.Optimization.FinitePenalizedProblem.optimizer_tie_eq_switchingPrice
#print axioms StrategyInnovation.Optimization.FinitePenalizedProblem.optimizer_tie_mem_pairwiseSwitchingPrices
#print axioms StrategyInnovation.Optimization.FinitePenalizedProblem.optimizer_burdens_eq_of_not_mem_pairwiseSwitchingPrices
#print axioms StrategyInnovation.Optimization.FinitePenalizedProblem.exists_eventuallyEq_branch_of_not_mem_pairwiseSwitchingPrices
#print axioms StrategyInnovation.Optimization.FinitePenalizedProblem.IsLocallyAffineAt
#print axioms StrategyInnovation.Optimization.FinitePenalizedProblem.breakpointSet
#print axioms StrategyInnovation.Optimization.FinitePenalizedProblem.isLocallyAffineAt_of_not_mem_pairwiseSwitchingPrices
#print axioms StrategyInnovation.Optimization.FinitePenalizedProblem.breakpointSet_subset_pairwiseSwitchingPrices
#print axioms StrategyInnovation.Optimization.FinitePenalizedProblem.breakpointSet_finite
#print axioms StrategyInnovation.Optimization.FinitePenalizedProblem.exists_hasDerivAt_envelope_of_not_mem_breakpointSet
#print axioms StrategyInnovation.Optimization.FinitePenalizedProblem.exists_hasDerivAt_envelope_of_not_mem_pairwiseSwitchingPrices
#print axioms StrategyInnovation.Optimization.FinitePenalizedProblem.StrictlyDominatesOn
#print axioms StrategyInnovation.Optimization.FinitePenalizedProblem.envelope_eq_branch_of_strictlyDominatesOn
#print axioms StrategyInnovation.Optimization.FinitePenalizedProblem.hasDerivAt_envelope_of_strictlyDominatesOn
#print axioms StrategyInnovation.Optimization.FinitePenalizedProblem.optimalBurden_antitone
#print axioms StrategyInnovation.Optimization.FinitePenalizedProblem.selectedOptimizer
#print axioms StrategyInnovation.Optimization.FinitePenalizedProblem.selectedOptimizer_isOptimizer
#print axioms StrategyInnovation.Optimization.FinitePenalizedProblem.selectedBurden_antitone

#lint- only checkType unusedArguments simpNF in StrategyInnovation.Optimization.FinitePenalizedProblem
