import StrategyInnovation.Optimization.SafeCompressionCounterexample

/-!
# Optimization T2--T4 safe-compression audit

This audit covers the manuscript-facing exact-safe feasibility,
dynamic-equivalence, value/action preservation, irreducibility, rechecked
endpoint, and registered global-greedy counterexample declarations.
-/

#print axioms StrategyInnovation.Optimization.SafeCompressionFeasible
#print axioms StrategyInnovation.Optimization.DynamicEquivalentSafeCompressionFeasible
#print axioms StrategyInnovation.Optimization.OneDeletionIrreducible
#print axioms StrategyInnovation.Optimization.MinimumWeightSafeCompression
#print axioms StrategyInnovation.Optimization.exists_minimumWeightSafeCompression
#print axioms StrategyInnovation.Optimization.safeCompressionFeasible_iff_dynamicEquivalentFeasible
#print axioms StrategyInnovation.Optimization.SafeCompressionFeasible.dynamicInnovationEquivalent
#print axioms StrategyInnovation.Optimization.SafeCompressionFeasible.preserves_finiteHorizonValue
#print axioms StrategyInnovation.Optimization.SafeCompressionFeasible.preserves_infiniteHorizonValue
#print axioms StrategyInnovation.Optimization.optimalFixedPointActions
#print axioms StrategyInnovation.Optimization.isOptimalFixedPointAction_iff_of_compressedState_eq
#print axioms StrategyInnovation.Optimization.SafeCompressionFeasible.preserves_optimalActions
#print axioms StrategyInnovation.Optimization.MinimumWeightSafeCompression.oneDeletionIrreducible
#print axioms StrategyInnovation.Optimization.recheckedSafeDeletionEndpoint_feasible
#print axioms StrategyInnovation.Optimization.SafeCompressionCounterexample.bundleFirst_recheckedSequence
#print axioms StrategyInnovation.Optimization.SafeCompressionCounterexample.pair_safeCompressionFeasible
#print axioms StrategyInnovation.Optimization.SafeCompressionCounterexample.pair_oneDeletionIrreducible
#print axioms StrategyInnovation.Optimization.SafeCompressionCounterexample.pair_not_minimumWeightSafeCompression
#print axioms StrategyInnovation.Optimization.SafeCompressionCounterexample.recheckedEndpoint_need_not_be_globallyMinimum
#print axioms StrategyInnovation.Optimization.SafeCompressionCounterexample.bundleFirst_rechecked_not_globallyOptimal
#print axioms StrategyInnovation.Optimization.SafeCompressionCounterexample.bundle_is_uniqueHeaviestSafeDeletion
#print axioms StrategyInnovation.Optimization.SafeCompressionCounterexample.strictHeaviestFirst_greedy_not_globallyOptimal

#lint- only checkType unusedArguments simpNF in StrategyInnovation.Optimization
#lint- only checkType unusedArguments simpNF in StrategyInnovation.Optimization.SafeCompressionCounterexample
