import StrategyInnovation.Compression.UnifiedSafeDeletionExamples

/-!
# T3 unified innovation-safe deletion audit

This file prints the kernel dependencies of every publication-facing T3
declaration and every exact boundary example.
-/

#print axioms StrategyInnovation.Projection.Model.operationallyRedundant
#print axioms StrategyInnovation.Projection.Model.generativelyRedundant
#print axioms StrategyInnovation.Projection.Model.RedundantDeletion
#print axioms StrategyInnovation.Projection.Model.InnovationSafeDeletion
#print axioms StrategyInnovation.Projection.Model.redundantDeletion_compressedLibraryState_eq
#print axioms StrategyInnovation.Projection.Model.redundantDeletion_iff_compressedLibraryState_eq
#print axioms StrategyInnovation.Projection.Model.redundantDeletion_dynamicInnovationEquivalent
#print axioms StrategyInnovation.Projection.Model.redundantDeletion_preserves_finiteHorizonValue
#print axioms StrategyInnovation.Projection.Model.redundantDeletion_innovationSafe
#print axioms StrategyInnovation.Projection.Model.InnovationSafeDeletion.projectCost
#print axioms StrategyInnovation.Projection.Model.InnovationSafeDeletion.projectDuration
#print axioms StrategyInnovation.Projection.Model.InnovationSafeDeletion.nextStateLaw
#print axioms StrategyInnovation.Projection.Model.InnovationSafeDeletion.operatingReward
#print axioms StrategyInnovation.Projection.Model.DiscountedContractionModel.redundantDeletion_preserves_infiniteHorizonValue
#print axioms StrategyInnovation.Projection.Model.stationaryActionAvailable
#print axioms StrategyInnovation.Projection.Model.fixedPointActionValue
#print axioms StrategyInnovation.Projection.Model.IsOptimalFixedPointAction
#print axioms StrategyInnovation.Projection.Model.DiscountedContractionModel.redundantDeletion_preserves_actionValueComparison
#print axioms StrategyInnovation.Projection.Model.DiscountedContractionModel.redundantDeletion_preserves_optimalAction
#print axioms StrategyInnovation.Projection.Model.deletionProcessObservations_iff_redundant
#print axioms StrategyInnovation.Projection.Model.innovationSafeDeletion_iff_redundant
#print axioms StrategyInnovation.Projection.Model.RedundantDeletionSequence
#print axioms StrategyInnovation.Projection.Model.InnovationSafeDeletionSequence
#print axioms StrategyInnovation.Projection.Model.RedundantDeletionSequence.final_le_initial
#print axioms StrategyInnovation.Projection.Model.RedundantDeletionSequence.compressedLibraryState_final_eq_initial
#print axioms StrategyInnovation.Projection.Model.RedundantDeletionSequence.everyDeletion_innovationSafe
#print axioms StrategyInnovation.Projection.Model.RedundantDeletionSequence.dynamicInnovationEquivalent
#print axioms StrategyInnovation.Projection.Model.RedundantDeletionSequence.preserves_finiteHorizonValue
#print axioms StrategyInnovation.Projection.Model.RedundantDeletionSequence.preserves_infiniteHorizonValue
#print axioms StrategyInnovation.Projection.Model.PruningAlgorithmSpec
#print axioms StrategyInnovation.Projection.Model.PruningAlgorithmSpec.everyDeletion_safe
#print axioms StrategyInnovation.Projection.Model.PruningAlgorithmSpec.output_dynamicInnovationEquivalent
#print axioms StrategyInnovation.Projection.Model.PruningAlgorithmSpec.output_preserves_finiteHorizonValue

#print axioms StrategyInnovation.Projection.Model.UnifiedSafeDeletionExamples.duplicateLeft_innovationSafe
#print axioms StrategyInnovation.Projection.Model.UnifiedSafeDeletionExamples.moduleOnly_operationallyRedundant_generativelyEssential
#print axioms StrategyInnovation.Projection.Model.UnifiedSafeDeletionExamples.operationalOnly_generativelyRedundant_operationallyEssential
#print axioms StrategyInnovation.Projection.Model.UnifiedSafeDeletionExamples.duplicateEncoding_orderChangesRawRepresentative
#print axioms StrategyInnovation.Projection.Model.UnifiedSafeDeletionExamples.stale_doubleDeletion_changes_compressedState
#print axioms StrategyInnovation.Projection.Model.UnifiedSafeDeletionExamples.staleOriginalRedundancyChecks_doNotCompose

#lint- only checkType unusedArguments simpNF in StrategyInnovation.Projection.Model
