module AORJournalArtifacts

using StrategyInnovation

include(joinpath(@__DIR__, "..", "..", "..", "julia", "scripts", "run_approximate_compression.jl"))
using .ApproximateCompressionExperiment

const REPOSITORY_ROOT = normpath(joinpath(@__DIR__, "..", "..", ".."))
const OUTPUT = joinpath(
    REPOSITORY_ROOT,
    "journal",
    "aor",
    "generated",
    "approximate_compression_summary.tex",
)

_ratio(value::Rational) =
    denominator(value) == 1 ? string(numerator(value)) :
    "$(numerator(value))/$(denominator(value))"
_ratio(value::Integer) = string(value)

function _algorithm_row(experiment, benchmark, method; beam_width = missing)
    rows = filter(
        row ->
            row.benchmark == benchmark &&
            row.method == method &&
            (beam_width === missing || row.beam_width == beam_width),
        experiment.algorithm_rows,
    )
    length(rows) == 1 || error("journal algorithm row did not resolve uniquely")
    return only(rows)
end

function render(experiment)
    benchmarks = ("base", "expanded")
    exact = Dict(
        benchmark => _algorithm_row(experiment, benchmark, :exact_enumeration) for
        benchmark in benchmarks
    )
    ip = Dict(
        benchmark => only(row for row in experiment.ip_rows if row.benchmark == benchmark) for
        benchmark in benchmarks
    )
    max_width = maximum(experiment.config["beam_widths"])
    expanded_beam = _algorithm_row(
        experiment,
        "expanded",
        :pareto_beam;
        beam_width = max_width,
    )

    io = IOBuffer()
    println(io, "% Generated by journal/aor/scripts/generate_journal_artifacts.jl.")
    println(io, "% Source: committed approximate-library-compression-v1 artifacts.")
    println(io, "\\newcommand{\\AORApproximateBenchmarkCount}{$(length(benchmarks))}")
    println(io, "\\newcommand{\\AORApproximateSubsetCount}{$(sum(row.total_subsets for row in values(exact)))}")
    println(io, "\\newcommand{\\AORApproximateGreedyRuleCount}{$(length(ApproximateCompressionExperiment.GREEDY_CRITERIA))}")
    println(io, "\\newcommand{\\AORApproximateMaximumBeamWidth}{$max_width}")
    println(io, "\\newcommand{\\AORApproximateExpandedBeamEvaluated}{$(expanded_beam.evaluated_count)}")
    println(io, "\\newcommand{\\AORApproximateExpandedSubsets}{$(expanded_beam.total_subsets)}")
    println(io, "\\newcommand{\\AORApproximateCompressionTable}{%")
    println(io, "\\begin{tabular}{@{}lrrrrrr@{}}")
    println(io, "\\toprule")
    println(
        io,
        raw"Benchmark & Source & Retained & Removed share & $\mathrm{OpLoss}$ & $\mathrm{GenLoss}$ & IP LB \\\\",
    )
    println(io, "\\midrule")
    for benchmark in benchmarks
        row = exact[benchmark]
        label = benchmark == "base" ? "Base" : "Expanded"
        println(
            io,
            "$label & $(row.source_size) & $(row.retained_size) & $(_ratio(row.compression_ratio)) & $(_ratio(row.operational_loss)) & $(_ratio(row.generative_loss)) & $(ip[benchmark].operational_cardinality_lower_bound) " *
            raw"\\\\",
        )
    end
    println(io, "\\botrule")
    println(io, "\\end{tabular}%")
    println(io, "}")
    return String(take!(io))
end

function main(args = ARGS)
    length(args) <= 1 || error("usage: generate_journal_artifacts.jl [--check]")
    check = !isempty(args) && only(args) == "--check"
    experiment = run_approximate_compression_experiment()
    generated = render(experiment)
    if check
        isfile(OUTPUT) || error("journal artifact is absent: $OUTPUT")
        read(OUTPUT, String) == generated || error("journal artifact drift: $OUTPUT")
        println("AOR journal artifact check passed: $OUTPUT")
    else
        mkpath(dirname(OUTPUT))
        write(OUTPUT, generated)
        println("Wrote $OUTPUT")
    end
    return nothing
end

end

if abspath(PROGRAM_FILE) == @__FILE__
    AORJournalArtifacts.main()
end
