import Mathlib.Data.Rat.Defs
import Mathlib.Tactic.NormNum

/-!
# Generated exact Lean–Julia consistency fixtures

This file is generated by `julia/scripts/export_exact_fixtures.jl` from the
same validated exact Julia objects that produce `shared/exact_fixtures/*.json`.
The examples below are kernel-checked fixture calculations. They establish
implementation agreement on these finite instances, not the corresponding
general mathematical theorems.
-/

namespace StrategyInnovation.Fixtures.Generated

set_option linter.unnecessarySeqFocus false
set_option linter.unreachableTactic false
set_option linter.unusedSimpArgs false
set_option linter.unusedTactic false

structure ExactStrategy where
  id : String
  operationalProfile : List ℚ
  modules : List String
  deriving Repr, DecidableEq

structure ExactLibrary where
  id : String
  strategies : List String
  deriving Repr, DecidableEq

structure ExactProject where
  id : String
  cost : List ℚ
  duration : Nat
  survival : ℚ
  strictCost : Bool
  requiredModules : List String
  candidateStrategies : List String
  deriving Repr, DecidableEq

structure ExactExpected where
  rationalScalars : List (String × ℚ)
  rationalVectors : List (String × List ℚ)
  booleanScalars : List (String × Bool)
  booleanVectors : List (String × List Bool)
  stringVectors : List (String × List String)
  deriving Repr, DecidableEq

structure ExactFixture where
  schemaVersion : String
  fixtureId : String
  theoremFamily : String
  beliefs : List String
  transitionRows : List (List ℚ)
  discount : ℚ
  modules : List String
  strategies : List ExactStrategy
  libraries : List ExactLibrary
  projects : List ExactProject
  expected : ExactExpected
  deriving Repr, DecidableEq

def lookupStrategy : List ExactStrategy → String → Option ExactStrategy
  | [], _ => none
  | row :: rows, id => if row.id = id then some row else lookupStrategy rows id

def lookupLibrary : List ExactLibrary → String → Option ExactLibrary
  | [], _ => none
  | row :: rows, id => if row.id = id then some row else lookupLibrary rows id

def lookupProject : List ExactProject → String → Option ExactProject
  | [], _ => none
  | row :: rows, id => if row.id = id then some row else lookupProject rows id

@[simp] def lookupRationalScalar : List (String × ℚ) → String → ℚ
  | [], _ => 0
  | row :: rows, id => if row.1 = id then row.2 else lookupRationalScalar rows id

@[simp] def lookupRationalVector : List (String × List ℚ) → String → List ℚ
  | [], _ => []
  | row :: rows, id => if row.1 = id then row.2 else lookupRationalVector rows id

@[simp] def lookupBooleanVector : List (String × List Bool) → String → List Bool
  | [], _ => []
  | row :: rows, id => if row.1 = id then row.2 else lookupBooleanVector rows id

def expectedRationalScalar (fixture : ExactFixture) (id : String) : ℚ :=
  lookupRationalScalar fixture.expected.rationalScalars id

def expectedRationalVector (fixture : ExactFixture) (id : String) : List ℚ :=
  lookupRationalVector fixture.expected.rationalVectors id

def expectedBooleanVector (fixture : ExactFixture) (id : String) : List Bool :=
  lookupBooleanVector fixture.expected.booleanVectors id

def atOr (values : List ℚ) (index : Nat) : ℚ := values.getD index 0

def profileAt (fixture : ExactFixture) (strategyId : String) (belief : Nat) : ℚ :=
  match lookupStrategy fixture.strategies strategyId with
  | none => 0
  | some row => atOr row.operationalProfile belief

def libraryStrategies (fixture : ExactFixture) (libraryId : String) : List String :=
  match lookupLibrary fixture.libraries libraryId with
  | none => []
  | some row => row.strategies

def frontierAt (fixture : ExactFixture) (libraryId : String) (belief : Nat) : ℚ :=
  (libraryStrategies fixture libraryId).foldl
    (fun best strategyId => max best (profileAt fixture strategyId belief)) 0

@[simp] def frontierAux
    (fixture : ExactFixture) (libraryId : String) : List String → Nat → List ℚ
  | [], _ => []
  | _ :: beliefs, index =>
      frontierAt fixture libraryId index :: frontierAux fixture libraryId beliefs (index + 1)

def frontier (fixture : ExactFixture) (libraryId : String) : List ℚ :=
  frontierAux fixture libraryId fixture.beliefs 0

@[simp] def strategySupplies (fixture : ExactFixture) (strategyId moduleId : String) : Bool :=
  match lookupStrategy fixture.strategies strategyId with
  | none => false
  | some row => row.modules.contains moduleId

@[simp] def moduleSupplied (fixture : ExactFixture) (libraryId moduleId : String) : Bool :=
  (libraryStrategies fixture libraryId).any
    (fun strategyId => strategySupplies fixture strategyId moduleId)

@[simp] def projectAvailable (fixture : ExactFixture) (libraryId projectId : String) : Bool :=
  match lookupProject fixture.projects projectId with
  | none => false
  | some row => row.requiredModules.all (moduleSupplied fixture libraryId)

def candidateGapAt
    (fixture : ExactFixture) (libraryId candidateId : String) (belief : Nat) : ℚ :=
  max (profileAt fixture candidateId belief - frontierAt fixture libraryId belief) 0

@[simp] def candidateGapAux
    (fixture : ExactFixture) (libraryId candidateId : String) : List String → Nat → List ℚ
  | [], _ => []
  | _ :: beliefs, index =>
      candidateGapAt fixture libraryId candidateId index ::
        candidateGapAux fixture libraryId candidateId beliefs (index + 1)

def candidateGap (fixture : ExactFixture) (libraryId candidateId : String) : List ℚ :=
  candidateGapAux fixture libraryId candidateId fixture.beliefs 0

def projectGapAt
    (fixture : ExactFixture) (libraryId : String) (candidateIds : List String)
    (belief : Nat) : ℚ :=
  candidateIds.foldl
    (fun total candidateId => total + candidateGapAt fixture libraryId candidateId belief) 0

@[simp] def projectGapAux
    (fixture : ExactFixture) (libraryId : String) (candidateIds : List String) :
    List String → Nat → List ℚ
  | [], _ => []
  | _ :: beliefs, index =>
      projectGapAt fixture libraryId candidateIds index ::
        projectGapAux fixture libraryId candidateIds beliefs (index + 1)

def projectGap (fixture : ExactFixture) (libraryId projectId : String) : List ℚ :=
  match lookupProject fixture.projects projectId with
  | none => []
  | some row => projectGapAux fixture libraryId row.candidateStrategies fixture.beliefs 0

def dot : List ℚ → List ℚ → ℚ
  | x :: xs, y :: ys => x * y + dot xs ys
  | _, _ => 0

def matrixVector (matrix : List (List ℚ)) (values : List ℚ) : List ℚ :=
  matrix.map (fun row => dot row values)

def addVectors : List ℚ → List ℚ → List ℚ
  | x :: xs, y :: ys => (x + y) :: addVectors xs ys
  | _, _ => []

def subVectors : List ℚ → List ℚ → List ℚ
  | x :: xs, y :: ys => (x - y) :: subVectors xs ys
  | _, _ => []

def scaleVector (scale : ℚ) : List ℚ → List ℚ
  | [] => []
  | x :: xs => scale * x :: scaleVector scale xs

def grossCoverage (fixture : ExactFixture) (libraryId projectId : String) : List ℚ :=
  scaleVector fixture.discount
    (matrixVector fixture.transitionRows (projectGap fixture libraryId projectId))

def eligibleGrossCoverage
    (fixture : ExactFixture) (libraryId projectId : String) : List ℚ :=
  if projectAvailable fixture libraryId projectId then
    grossCoverage fixture libraryId projectId
  else
    List.replicate fixture.beliefs.length 0

def discountedGapSum
    (transition : List (List ℚ)) (discount : ℚ) : Nat → List ℚ → List ℚ
  | 0, gap => List.replicate gap.length 0
  | horizon + 1, gap =>
      addVectors gap (scaleVector discount
        (matrixVector transition (discountedGapSum transition discount horizon gap)))

def persistenceKernel (persistence : ℚ) : List (List ℚ) :=
  [[persistence, 1 - persistence], [1 - persistence, persistence]]

def oneProjectPremium
    (discount frontier success cost candidate : ℚ) : ℚ :=
  max (discount * success * max (candidate - frontier) 0 - cost) 0

def closureIncrement
    (discount frontier oldSuccess addedSuccess oldCost addedCost candidate : ℚ) : ℚ :=
  max
      (oneProjectPremium discount frontier oldSuccess oldCost candidate)
      (oneProjectPremium discount frontier addedSuccess addedCost candidate) -
    oneProjectPremium discount frontier oldSuccess oldCost candidate

def projectCost (fixture : ExactFixture) (projectId : String) : List ℚ :=
  match lookupProject fixture.projects projectId with
  | none => []
  | some row => row.cost

def weakRegion : List ℚ → List ℚ → List Bool
  | value :: values, cost :: costs => decide (cost ≤ value) :: weakRegion values costs
  | _, _ => []

def strictRegion : List ℚ → List ℚ → List Bool
  | value :: values, cost :: costs => decide (cost < value) :: strictRegion values costs
  | _, _ => []

def researchRegion (fixture : ExactFixture) (libraryId projectId : String) : List Bool :=
  match lookupProject fixture.projects projectId with
  | none => []
  | some row =>
      if row.strictCost then
        strictRegion (grossCoverage fixture libraryId projectId) row.cost
      else
        weakRegion (grossCoverage fixture libraryId projectId) row.cost

def componentCountAux : List Bool → Bool → Nat
  | [], _ => 0
  | value :: values, inside =>
      (if value && !inside then 1 else 0) + componentCountAux values value

def componentCount (region : List Bool) : Nat := componentCountAux region false

def passiveValue (fixture : ExactFixture) (libraryId : String) : ℚ :=
  frontierAt fixture libraryId 0

def fullValue (fixture : ExactFixture) (libraryId projectId : String) : ℚ :=
  passiveValue fixture libraryId + atOr (eligibleGrossCoverage fixture libraryId projectId) 0

namespace CurrentZeroFuturePositive

def fixture : ExactFixture :=
  ExactFixture.mk
  "lean-julia-exact-fixture-v2"
  "current_zero_future_positive"
  "F7 current-zero future-positive compatibility fixture"
  ["current", "future"]
  [[0, 1], [0, 1]]
  (1 / 2 : ℚ)
  ["marker"]
  [ExactStrategy.mk "inactive" [0, 0] [], ExactStrategy.mk "candidate" [0, 2] ["marker"]]
  [ExactLibrary.mk "current" ["inactive"]]
  [ExactProject.mk "innovate" [0, 0] 1 1 false [] ["candidate"]]
  (ExactExpected.mk
    [("current_gap", 0), ("future_gap", 2), ("initial_innovation_value", 1)]
    [("candidate_gap", [0, 2]), ("discounted_gap_sum_horizon_two", [1, 3])]
    [("current_gap_zero", true), ("future_gap_positive", true), ("innovation_value_positive", true)]
    []
    [])

def gap : List ℚ := candidateGap fixture "current" "candidate"
def innovationValue : List ℚ := discountedGapSum fixture.transitionRows fixture.discount 2 gap
example : gap = [0, 2] := by simp [gap, candidateGap, candidateGapAt, frontierAt, libraryStrategies, profileAt, lookupLibrary, lookupStrategy, atOr, fixture] <;> norm_num
example : atOr gap 0 = 0 := by simp [gap, candidateGap, candidateGapAt, frontierAt, libraryStrategies, profileAt, lookupLibrary, lookupStrategy, atOr, fixture] <;> norm_num
example : atOr gap 1 > 0 := by simp [gap, candidateGap, candidateGapAt, frontierAt, libraryStrategies, profileAt, lookupLibrary, lookupStrategy, atOr, fixture] <;> norm_num
example : innovationValue = [1, 3] := by simp [innovationValue, discountedGapSum, gap, candidateGap, candidateGapAt, frontierAt, libraryStrategies, profileAt, lookupLibrary, lookupStrategy, matrixVector, dot, addVectors, scaleVector, atOr, fixture] <;> norm_num
example : innovationValue = expectedRationalVector fixture "discounted_gap_sum_horizon_two" := by simp [expectedRationalVector, innovationValue, discountedGapSum, gap, candidateGap, candidateGapAt, frontierAt, libraryStrategies, profileAt, lookupLibrary, lookupStrategy, matrixVector, dot, addVectors, scaleVector, atOr, fixture] <;> norm_num

end CurrentZeroFuturePositive

namespace DiscountSurvivalComplementarity

def fixture : ExactFixture :=
  ExactFixture.mk
  "lean-julia-exact-fixture-v2"
  "discount_survival_complementarity"
  "S6 discount-survival complementarity"
  ["low", "high"]
  [[(3 / 4 : ℚ), (1 / 4 : ℚ)], [(1 / 2 : ℚ), (1 / 2 : ℚ)]]
  (3 / 4 : ℚ)
  ["marker"]
  [ExactStrategy.mk "inactive" [0, 0] [], ExactStrategy.mk "candidate" [1, 3] ["marker"]]
  [ExactLibrary.mk "current" ["inactive"]]
  [ExactProject.mk "innovate" [0, 0] 1 (2 / 3 : ℚ) false [] ["candidate"]]
  (ExactExpected.mk
    [("beta_high", (3 / 4 : ℚ)), ("beta_low", (1 / 4 : ℚ)), ("horizon", 5), ("survival_high", (2 / 3 : ℚ)), ("survival_low", (1 / 3 : ℚ))]
    [("cross_difference", [(43771 / 55296 : ℚ), (24869 / 27648 : ℚ)]), ("factorized_cross_difference", [(43771 / 55296 : ℚ), (24869 / 27648 : ℚ)]), ("potential_high_beta_high_survival", [(5053 / 2048 : ℚ), (4867 / 1024 : ℚ)]), ("potential_high_beta_low_survival", [(49445 / 32768 : ℚ), (59675 / 16384 : ℚ)]), ("potential_low_beta_high_survival", [(24037 / 18432 : ℚ), (281267 / 82944 : ℚ)]), ("potential_low_beta_low_survival", [(1006231 / 884736 : ℚ), (4220027 / 1327104 : ℚ)])]
    [("cross_difference_nonnegative", true), ("factorization_holds", true)]
    []
    [])

def gap : List ℚ := candidateGap fixture "current" "candidate"
def potential00 : List ℚ := discountedGapSum fixture.transitionRows ((1 / 4 : ℚ) * (1 / 3 : ℚ)) 5 gap
def potential10 : List ℚ := discountedGapSum fixture.transitionRows ((3 / 4 : ℚ) * (1 / 3 : ℚ)) 5 gap
def potential01 : List ℚ := discountedGapSum fixture.transitionRows ((1 / 4 : ℚ) * (2 / 3 : ℚ)) 5 gap
def potential11 : List ℚ := discountedGapSum fixture.transitionRows ((3 / 4 : ℚ) * (2 / 3 : ℚ)) 5 gap
def crossDifference : List ℚ :=
  subVectors (addVectors potential11 potential00) (addVectors potential10 potential01)
example : potential00 = expectedRationalVector fixture "potential_low_beta_low_survival" := by simp [potential00, gap, discountedGapSum, candidateGap, candidateGapAt, frontierAt, libraryStrategies, profileAt, lookupLibrary, lookupStrategy, matrixVector, dot, addVectors, scaleVector, atOr, expectedRationalVector, fixture] <;> norm_num
example : potential11 = expectedRationalVector fixture "potential_high_beta_high_survival" := by simp [potential11, gap, discountedGapSum, candidateGap, candidateGapAt, frontierAt, libraryStrategies, profileAt, lookupLibrary, lookupStrategy, matrixVector, dot, addVectors, scaleVector, atOr, expectedRationalVector, fixture] <;> norm_num
example : crossDifference = expectedRationalVector fixture "cross_difference" := by simp [crossDifference, potential00, potential10, potential01, potential11, gap, discountedGapSum, candidateGap, candidateGapAt, frontierAt, libraryStrategies, profileAt, lookupLibrary, lookupStrategy, matrixVector, dot, addVectors, subVectors, scaleVector, atOr, expectedRationalVector, fixture] <;> norm_num
example : crossDifference = [(43771 / 55296 : ℚ), (24869 / 27648 : ℚ)] := by simp [crossDifference, potential00, potential10, potential01, potential11, gap, discountedGapSum, candidateGap, candidateGapAt, frontierAt, libraryStrategies, profileAt, lookupLibrary, lookupStrategy, matrixVector, dot, addVectors, subVectors, scaleVector, atOr, fixture] <;> norm_num

end DiscountSurvivalComplementarity

namespace FrontierClosureComplementarity

def fixture : ExactFixture :=
  ExactFixture.mk
  "lean-julia-exact-fixture-v2"
  "frontier_closure_complementarity"
  "T7 frontier-closure complementarity boundary"
  ["only"]
  [[1]]
  (1 / 2 : ℚ)
  ["old", "added"]
  [ExactStrategy.mk "inactive" [0] [], ExactStrategy.mk "frontier_high" [8] [], ExactStrategy.mk "candidate" [10] []]
  [ExactLibrary.mk "frontier_low" ["inactive"], ExactLibrary.mk "frontier_high" ["inactive", "frontier_high"]]
  [ExactProject.mk "old_project" [2] 1 1 false ["old"] ["candidate"], ExactProject.mk "added_project" [0] 1 (1 / 2 : ℚ) false ["added"] ["candidate"]]
  (ExactExpected.mk
    [("added_cost", 0), ("added_success", (1 / 2 : ℚ)), ("candidate_quality", 10), ("closure_increment_high_frontier", (1 / 2 : ℚ)), ("closure_increment_low_frontier", 0), ("cross_difference", (1 / 2 : ℚ)), ("frontier_high", 8), ("frontier_low", 0), ("old_cost", 2), ("old_success", 1)]
    []
    [("is_complementarity", true), ("is_substitution", false)]
    []
    [])

def lowIncrement : ℚ := closureIncrement fixture.discount 0 1 (1 / 2 : ℚ) 2 0 10
def highIncrement : ℚ := closureIncrement fixture.discount 8 1 (1 / 2 : ℚ) 2 0 10
def interaction : ℚ := highIncrement - lowIncrement
example : lowIncrement = 0 := by simp [lowIncrement, closureIncrement, oneProjectPremium, fixture] <;> norm_num
example : highIncrement = (1 / 2 : ℚ) := by simp [highIncrement, closureIncrement, oneProjectPremium, fixture] <;> norm_num
example : interaction = (1 / 2 : ℚ) := by simp [interaction, lowIncrement, highIncrement, closureIncrement, oneProjectPremium, fixture] <;> norm_num
example : interaction = expectedRationalScalar fixture "cross_difference" := by simp [interaction, lowIncrement, highIncrement, closureIncrement, oneProjectPremium, expectedRationalScalar, fixture] <;> norm_num

end FrontierClosureComplementarity

namespace FrontierClosureSubstitution

def fixture : ExactFixture :=
  ExactFixture.mk
  "lean-julia-exact-fixture-v2"
  "frontier_closure_substitution"
  "T7 frontier-closure substitution"
  ["only"]
  [[1]]
  (1 / 2 : ℚ)
  ["old", "added"]
  [ExactStrategy.mk "inactive" [0] [], ExactStrategy.mk "frontier_high" [2] [], ExactStrategy.mk "candidate" [4] []]
  [ExactLibrary.mk "frontier_low" ["inactive"], ExactLibrary.mk "frontier_high" ["inactive", "frontier_high"]]
  [ExactProject.mk "old_project" [0] 1 0 false ["old"] ["candidate"], ExactProject.mk "added_project" [0] 1 1 false ["added"] ["candidate"]]
  (ExactExpected.mk
    [("added_cost", 0), ("added_success", 1), ("candidate_quality", 4), ("closure_increment_high_frontier", 1), ("closure_increment_low_frontier", 2), ("cross_difference", -1), ("frontier_high", 2), ("frontier_low", 0), ("old_cost", 0), ("old_success", 0)]
    []
    [("is_complementarity", false), ("is_substitution", true)]
    []
    [])

def lowIncrement : ℚ := closureIncrement fixture.discount 0 0 1 0 0 4
def highIncrement : ℚ := closureIncrement fixture.discount 2 0 1 0 0 4
def interaction : ℚ := highIncrement - lowIncrement
example : lowIncrement = 2 := by simp [lowIncrement, closureIncrement, oneProjectPremium, fixture] <;> norm_num
example : highIncrement = 1 := by simp [highIncrement, closureIncrement, oneProjectPremium, fixture] <;> norm_num
example : interaction = -1 := by simp [interaction, lowIncrement, highIncrement, closureIncrement, oneProjectPremium, fixture] <;> norm_num
example : interaction = expectedRationalScalar fixture "cross_difference" := by simp [interaction, lowIncrement, highIncrement, closureIncrement, oneProjectPremium, expectedRationalScalar, fixture] <;> norm_num

end FrontierClosureSubstitution

namespace FrontierPruningLoss

def fixture : ExactFixture :=
  ExactFixture.mk
  "lean-julia-exact-fixture-v2"
  "frontier_pruning_loss"
  "F4 arbitrary frontier-pruning loss compatibility fixture"
  ["only"]
  [[1]]
  (1 / 2 : ℚ)
  ["key"]
  [ExactStrategy.mk "inactive" [0] [], ExactStrategy.mk "bridge" [0] ["key"], ExactStrategy.mk "future" [10] []]
  [ExactLibrary.mk "pruned" ["inactive"], ExactLibrary.mk "unpruned" ["inactive", "bridge"]]
  [ExactProject.mk "innovate" [0] 1 1 false ["key"] ["future"]]
  (ExactExpected.mk
    [("pruned_research_value", 0), ("research_value_loss", 5), ("unpruned_research_value", 5)]
    [("frontier_pruned", [0]), ("frontier_unpruned", [0])]
    [("frontier_preserved", true), ("generative_closure_preserved", false), ("loss_positive", true)]
    []
    [("modules_pruned", []), ("modules_unpruned", ["key"])])

example : frontier fixture "unpruned" = frontier fixture "pruned" := by simp [frontier, frontierAt, libraryStrategies, profileAt, lookupLibrary, lookupStrategy, atOr, fixture] <;> norm_num
example : moduleSupplied fixture "unpruned" "key" = true := by simp [moduleSupplied, libraryStrategies, strategySupplies, lookupLibrary, lookupStrategy, fixture] <;> norm_num
example : moduleSupplied fixture "pruned" "key" = false := by simp [moduleSupplied, libraryStrategies, strategySupplies, lookupLibrary, lookupStrategy, fixture] <;> norm_num
example : atOr (eligibleGrossCoverage fixture "unpruned" "innovate") 0 = 5 := by simp [eligibleGrossCoverage, projectAvailable, grossCoverage, projectGap, projectGapAt, candidateGapAt, frontierAt, libraryStrategies, profileAt, lookupProject, lookupLibrary, lookupStrategy, matrixVector, dot, scaleVector, atOr, fixture] <;> norm_num
example : atOr (eligibleGrossCoverage fixture "pruned" "innovate") 0 = 0 := by simp [eligibleGrossCoverage, projectAvailable, libraryStrategies, strategySupplies, lookupProject, lookupLibrary, lookupStrategy, atOr, fixture] <;> norm_num
example : atOr (eligibleGrossCoverage fixture "unpruned" "innovate") 0 = expectedRationalScalar fixture "unpruned_research_value" := by simp [expectedRationalScalar, eligibleGrossCoverage, projectAvailable, grossCoverage, projectGap, projectGapAt, candidateGapAt, frontierAt, libraryStrategies, profileAt, lookupProject, lookupLibrary, lookupStrategy, matrixVector, dot, scaleVector, atOr, fixture] <;> norm_num

end FrontierPruningLoss

namespace GenerativeLowerBound

def fixture : ExactFixture :=
  ExactFixture.mk
  "lean-julia-exact-fixture-v2"
  "generative_lower_bound"
  "T6 retained-carrier generative lower bound"
  ["only"]
  [[1]]
  (1 / 2 : ℚ)
  ["key"]
  [ExactStrategy.mk "inactive" [0] [], ExactStrategy.mk "bridge" [0] ["key"], ExactStrategy.mk "candidate" [2] []]
  [ExactLibrary.mk "current" ["inactive", "bridge"]]
  [ExactProject.mk "innovate" [0] 1 1 false ["key"] ["candidate"]]
  (ExactExpected.mk
    [("admission_probability", 1), ("expected_completion_gain", 2), ("lower_bound", 1), ("operating_adjustment", 0), ("research_cost", 0), ("survival_factor", 1)]
    [("completion_gains", [2]), ("occupation_weights", [1])]
    [("lower_bound_positive", true)]
    []
    [])

def lowerBoundFormula : ℚ :=
  max
    (-expectedRationalScalar fixture "research_cost" +
      expectedRationalScalar fixture "operating_adjustment" +
      fixture.discount *
      expectedRationalScalar fixture "admission_probability" *
      expectedRationalScalar fixture "survival_factor" *
      expectedRationalScalar fixture "expected_completion_gain")
    0
example : lowerBoundFormula = 1 := by simp [lowerBoundFormula, expectedRationalScalar, fixture] <;> norm_num
example : lowerBoundFormula = expectedRationalScalar fixture "lower_bound" := by simp [lowerBoundFormula, expectedRationalScalar, fixture] <;> norm_num
example : expectedRationalScalar fixture "lower_bound" > 0 := by simp [expectedRationalScalar, fixture] <;> norm_num

end GenerativeLowerBound

namespace MonotoneGapThreshold

def fixture : ExactFixture :=
  ExactFixture.mk
  "lean-julia-exact-fixture-v2"
  "monotone_gap_threshold"
  "S5 monotone-gap threshold"
  ["b1", "b2", "b3", "b4"]
  [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]
  1
  ["marker"]
  [ExactStrategy.mk "inactive" [0, 0, 0, 0] [], ExactStrategy.mk "candidate" [0, (1 / 2 : ℚ), (3 / 2 : ℚ), 3] ["marker"]]
  [ExactLibrary.mk "current" ["inactive"]]
  [ExactProject.mk "innovate" [2, 1, (1 / 2 : ℚ), 0] 1 1 false [] ["candidate"]]
  (ExactExpected.mk
    [("connected_components", 1), ("threshold_cutoff_index", 3)]
    [("candidate_gap", [0, (1 / 2 : ℚ), (3 / 2 : ℚ), 3]), ("coverage_potential", [0, (1 / 2 : ℚ), (3 / 2 : ℚ), 3]), ("research_cost", [2, 1, (1 / 2 : ℚ), 0])]
    [("cost_antitone", true), ("gap_monotone", true), ("kernel_stochastically_monotone", true), ("upper_threshold", true)]
    [("research_region", [false, false, true, true])]
    [])

example : projectGap fixture "current" "innovate" = [0, (1 / 2 : ℚ), (3 / 2 : ℚ), 3] := by simp [projectGap, projectGapAt, candidateGapAt, frontierAt, libraryStrategies, profileAt, lookupProject, lookupLibrary, lookupStrategy, atOr, fixture] <;> norm_num
example : grossCoverage fixture "current" "innovate" = [0, (1 / 2 : ℚ), (3 / 2 : ℚ), 3] := by simp [grossCoverage, projectGap, projectGapAt, candidateGapAt, frontierAt, libraryStrategies, profileAt, lookupProject, lookupLibrary, lookupStrategy, matrixVector, dot, scaleVector, atOr, fixture] <;> norm_num
example : researchRegion fixture "current" "innovate" = [false, false, true, true] := by simp [researchRegion, weakRegion, grossCoverage, projectGap, projectGapAt, candidateGapAt, frontierAt, libraryStrategies, profileAt, lookupProject, lookupLibrary, lookupStrategy, matrixVector, dot, scaleVector, atOr, fixture] <;> norm_num
example : componentCount (researchRegion fixture "current" "innovate") = 1 := by simp [componentCount, componentCountAux, researchRegion, weakRegion, grossCoverage, projectGap, projectGapAt, candidateGapAt, frontierAt, libraryStrategies, profileAt, lookupProject, lookupLibrary, lookupStrategy, matrixVector, dot, scaleVector, atOr, fixture] <;> norm_num
example : researchRegion fixture "current" "innovate" = expectedBooleanVector fixture "research_region" := by simp [expectedBooleanVector, researchRegion, weakRegion, grossCoverage, projectGap, projectGapAt, candidateGapAt, frontierAt, libraryStrategies, profileAt, lookupProject, lookupLibrary, lookupStrategy, matrixVector, dot, scaleVector, atOr, fixture] <;> norm_num

end MonotoneGapThreshold

namespace MultiGapDisconnectedRegion

def fixture : ExactFixture :=
  ExactFixture.mk
  "lean-julia-exact-fixture-v2"
  "multi_gap_disconnected_region"
  "C2 disconnected-region compatibility fixture"
  ["b0", "b1", "b2", "b3", "b4"]
  [[1, 0, 0, 0, 0], [(81 / 256 : ℚ), (27 / 64 : ℚ), (27 / 128 : ℚ), (3 / 64 : ℚ), (1 / 256 : ℚ)], [(1 / 16 : ℚ), (1 / 4 : ℚ), (3 / 8 : ℚ), (1 / 4 : ℚ), (1 / 16 : ℚ)], [(1 / 256 : ℚ), (3 / 64 : ℚ), (27 / 128 : ℚ), (27 / 64 : ℚ), (81 / 256 : ℚ)], [0, 0, 0, 0, 1]]
  1
  ["marker"]
  [ExactStrategy.mk "inactive" [0, 0, 0, 0, 0] [], ExactStrategy.mk "left_candidate" [4, 0, 0, 0, 0] ["marker"], ExactStrategy.mk "right_candidate" [0, 0, 0, 0, 4] ["marker"]]
  [ExactLibrary.mk "current" ["inactive"]]
  [ExactProject.mk "innovate" [1, 1, 1, 1, 1] 1 1 true [] ["left_candidate", "right_candidate"]]
  (ExactExpected.mk
    [("connected_components", 2)]
    [("aggregate_gap", [4, 0, 0, 0, 4]), ("coverage_potential", [4, (41 / 32 : ℚ), (1 / 2 : ℚ), (41 / 32 : ℚ), 4]), ("left_gap", [4, 0, 0, 0, 0]), ("right_gap", [0, 0, 0, 0, 4])]
    [("region_disconnected", true)]
    [("research_region", [true, true, false, true, true])]
    [])

example : projectGap fixture "current" "innovate" = [4, 0, 0, 0, 4] := by simp [projectGap, projectGapAt, candidateGapAt, frontierAt, libraryStrategies, profileAt, lookupProject, lookupLibrary, lookupStrategy, atOr, fixture] <;> norm_num
example : grossCoverage fixture "current" "innovate" = [4, (41 / 32 : ℚ), (1 / 2 : ℚ), (41 / 32 : ℚ), 4] := by simp [grossCoverage, projectGap, projectGapAt, candidateGapAt, frontierAt, libraryStrategies, profileAt, lookupProject, lookupLibrary, lookupStrategy, matrixVector, dot, scaleVector, atOr, fixture] <;> norm_num
example : researchRegion fixture "current" "innovate" = [true, true, false, true, true] := by simp [researchRegion, strictRegion, grossCoverage, projectGap, projectGapAt, candidateGapAt, frontierAt, libraryStrategies, profileAt, lookupProject, lookupLibrary, lookupStrategy, matrixVector, dot, scaleVector, atOr, fixture] <;> norm_num
example : componentCount (researchRegion fixture "current" "innovate") = 2 := by simp [componentCount, componentCountAux, researchRegion, strictRegion, grossCoverage, projectGap, projectGapAt, candidateGapAt, frontierAt, libraryStrategies, profileAt, lookupProject, lookupLibrary, lookupStrategy, matrixVector, dot, scaleVector, atOr, fixture] <;> norm_num
example : researchRegion fixture "current" "innovate" = expectedBooleanVector fixture "research_region" := by simp [expectedBooleanVector, researchRegion, strictRegion, grossCoverage, projectGap, projectGapAt, candidateGapAt, frontierAt, libraryStrategies, profileAt, lookupProject, lookupLibrary, lookupStrategy, matrixVector, dot, scaleVector, atOr, fixture] <;> norm_num

end MultiGapDisconnectedRegion

namespace MultiGapDisconnection

def fixture : ExactFixture :=
  ExactFixture.mk
  "lean-julia-exact-fixture-v2"
  "multi_gap_disconnection"
  "C2 multi-gap disconnection"
  ["b0", "b1", "b2", "b3", "b4"]
  [[1, 0, 0, 0, 0], [(81 / 256 : ℚ), (27 / 64 : ℚ), (27 / 128 : ℚ), (3 / 64 : ℚ), (1 / 256 : ℚ)], [(1 / 16 : ℚ), (1 / 4 : ℚ), (3 / 8 : ℚ), (1 / 4 : ℚ), (1 / 16 : ℚ)], [(1 / 256 : ℚ), (3 / 64 : ℚ), (27 / 128 : ℚ), (27 / 64 : ℚ), (81 / 256 : ℚ)], [0, 0, 0, 0, 1]]
  1
  ["marker"]
  [ExactStrategy.mk "inactive" [0, 0, 0, 0, 0] [], ExactStrategy.mk "left_candidate" [4, 0, 0, 0, 0] ["marker"], ExactStrategy.mk "right_candidate" [0, 0, 0, 0, 4] ["marker"]]
  [ExactLibrary.mk "current" ["inactive"]]
  [ExactProject.mk "innovate" [1, 1, 1, 1, 1] 1 1 true [] ["left_candidate", "right_candidate"]]
  (ExactExpected.mk
    [("connected_components", 2)]
    [("aggregate_gap", [4, 0, 0, 0, 4]), ("coverage_potential", [4, (41 / 32 : ℚ), (1 / 2 : ℚ), (41 / 32 : ℚ), 4]), ("left_gap", [4, 0, 0, 0, 0]), ("right_gap", [0, 0, 0, 0, 4])]
    [("region_disconnected", true)]
    [("research_region", [true, true, false, true, true])]
    [])

example : projectGap fixture "current" "innovate" = [4, 0, 0, 0, 4] := by simp [projectGap, projectGapAt, candidateGapAt, frontierAt, libraryStrategies, profileAt, lookupProject, lookupLibrary, lookupStrategy, atOr, fixture] <;> norm_num
example : grossCoverage fixture "current" "innovate" = [4, (41 / 32 : ℚ), (1 / 2 : ℚ), (41 / 32 : ℚ), 4] := by simp [grossCoverage, projectGap, projectGapAt, candidateGapAt, frontierAt, libraryStrategies, profileAt, lookupProject, lookupLibrary, lookupStrategy, matrixVector, dot, scaleVector, atOr, fixture] <;> norm_num
example : researchRegion fixture "current" "innovate" = [true, true, false, true, true] := by simp [researchRegion, strictRegion, grossCoverage, projectGap, projectGapAt, candidateGapAt, frontierAt, libraryStrategies, profileAt, lookupProject, lookupLibrary, lookupStrategy, matrixVector, dot, scaleVector, atOr, fixture] <;> norm_num
example : componentCount (researchRegion fixture "current" "innovate") = 2 := by simp [componentCount, componentCountAux, researchRegion, strictRegion, grossCoverage, projectGap, projectGapAt, candidateGapAt, frontierAt, libraryStrategies, profileAt, lookupProject, lookupLibrary, lookupStrategy, matrixVector, dot, scaleVector, atOr, fixture] <;> norm_num
example : researchRegion fixture "current" "innovate" = expectedBooleanVector fixture "research_region" := by simp [expectedBooleanVector, researchRegion, strictRegion, grossCoverage, projectGap, projectGapAt, candidateGapAt, frontierAt, libraryStrategies, profileAt, lookupProject, lookupLibrary, lookupStrategy, matrixVector, dot, scaleVector, atOr, fixture] <;> norm_num

end MultiGapDisconnection

namespace NormalizedPruningLoss

def fixture : ExactFixture :=
  ExactFixture.mk
  "lean-julia-exact-fixture-v2"
  "normalized_pruning_loss"
  "T4 sharp normalized pruning loss"
  ["only"]
  [[1]]
  (1 / 2 : ℚ)
  ["key"]
  [ExactStrategy.mk "inactive" [0] [], ExactStrategy.mk "bridge" [0] ["key"], ExactStrategy.mk "candidate" [2] []]
  [ExactLibrary.mk "pruned" ["inactive"], ExactLibrary.mk "unpruned" ["inactive", "bridge"]]
  [ExactProject.mk "innovate" [0] 1 1 false ["key"] ["candidate"]]
  (ExactExpected.mk
    [("admission_probability", 1), ("maximum_net_descendant_value", 1), ("normalized_pruning_loss", 1), ("pruned_value", 0), ("research_cost", 0), ("reward_cap", 2), ("unpruned_value", 1), ("value_loss", 1)]
    [("frontier_pruned", [0]), ("frontier_unpruned", [0])]
    [("frontier_preserved", true), ("normalization_attained", true)]
    []
    [("modules_pruned", []), ("modules_unpruned", ["key"])])

def lossFormula : ℚ :=
  max
    (fixture.discount *
      expectedRationalScalar fixture "admission_probability" *
      expectedRationalScalar fixture "reward_cap" -
      expectedRationalScalar fixture "research_cost")
    0
example : frontier fixture "unpruned" = frontier fixture "pruned" := by simp [frontier, frontierAt, libraryStrategies, profileAt, lookupLibrary, lookupStrategy, atOr, fixture] <;> norm_num
example : moduleSupplied fixture "unpruned" "key" = true := by simp [moduleSupplied, libraryStrategies, strategySupplies, lookupLibrary, lookupStrategy, fixture] <;> norm_num
example : moduleSupplied fixture "pruned" "key" = false := by simp [moduleSupplied, libraryStrategies, strategySupplies, lookupLibrary, lookupStrategy, fixture] <;> norm_num
example : lossFormula = 1 := by simp [lossFormula, expectedRationalScalar, fixture] <;> norm_num
example : lossFormula = expectedRationalScalar fixture "value_loss" := by simp [lossFormula, expectedRationalScalar, fixture] <;> norm_num
example : expectedRationalScalar fixture "normalized_pruning_loss" = 1 := by simp [expectedRationalScalar, fixture] <;> norm_num

end NormalizedPruningLoss

namespace OperationalGenerativeDecomposition

def fixture : ExactFixture :=
  ExactFixture.mk
  "lean-julia-exact-fixture-v2"
  "operational_generative_decomposition"
  "T5 operational-generative decomposition"
  ["only"]
  [[1]]
  (1 / 2 : ℚ)
  ["key"]
  [ExactStrategy.mk "inactive" [0] [], ExactStrategy.mk "bridge" [0] ["key"], ExactStrategy.mk "candidate" [2] []]
  [ExactLibrary.mk "baseline" ["inactive"], ExactLibrary.mk "inserted" ["inactive", "bridge"]]
  [ExactProject.mk "innovate" [0] 1 1 false ["key"] ["candidate"]]
  (ExactExpected.mk
    [("full_baseline", 0), ("full_inserted", 1), ("generative_component", 1), ("operational_component", 0), ("passive_baseline", 0), ("passive_inserted", 0), ("total_increment", 1)]
    []
    [("decomposition_identity", true), ("generative_component_positive", true)]
    []
    [])

def totalIncrement : ℚ := fullValue fixture "inserted" "innovate" - fullValue fixture "baseline" "innovate"
def operationalComponent : ℚ := passiveValue fixture "inserted" - passiveValue fixture "baseline"
def generativeComponent : ℚ := totalIncrement - operationalComponent
example : totalIncrement = 1 := by simp [totalIncrement, fullValue, passiveValue, eligibleGrossCoverage, projectAvailable, grossCoverage, projectGap, projectGapAt, candidateGapAt, frontierAt, libraryStrategies, profileAt, lookupProject, lookupLibrary, lookupStrategy, matrixVector, dot, scaleVector, atOr, fixture] <;> norm_num
example : operationalComponent = 0 := by simp [operationalComponent, passiveValue, frontierAt, libraryStrategies, profileAt, lookupLibrary, lookupStrategy, atOr, fixture] <;> norm_num
example : generativeComponent = 1 := by simp [generativeComponent, totalIncrement, operationalComponent, fullValue, passiveValue, eligibleGrossCoverage, projectAvailable, grossCoverage, projectGap, projectGapAt, candidateGapAt, frontierAt, libraryStrategies, profileAt, lookupProject, lookupLibrary, lookupStrategy, matrixVector, dot, scaleVector, atOr, fixture] <;> norm_num
example : totalIncrement = operationalComponent + generativeComponent := by simp [totalIncrement, operationalComponent, generativeComponent] <;> norm_num
example : totalIncrement = expectedRationalScalar fixture "total_increment" := by simp [expectedRationalScalar, totalIncrement, fullValue, passiveValue, eligibleGrossCoverage, projectAvailable, grossCoverage, projectGap, projectGapAt, candidateGapAt, frontierAt, libraryStrategies, profileAt, lookupProject, lookupLibrary, lookupStrategy, matrixVector, dot, scaleVector, atOr, fixture] <;> norm_num

end OperationalGenerativeDecomposition

namespace PersistenceDecreasesCoverage

def fixture : ExactFixture :=
  ExactFixture.mk
  "lean-julia-exact-fixture-v2"
  "persistence_decreases_coverage"
  "S7 persistence-decreases-coverage example"
  ["current", "other"]
  [[0, 1], [1, 0]]
  (1 / 2 : ℚ)
  ["marker"]
  [ExactStrategy.mk "inactive" [0, 0] [], ExactStrategy.mk "candidate" [0, 1] ["marker"]]
  [ExactLibrary.mk "current" ["inactive"]]
  [ExactProject.mk "innovate" [0, 0] 1 1 false [] ["candidate"]]
  (ExactExpected.mk
    [("coverage_high_persistence", (1 / 8 : ℚ)), ("coverage_low_persistence", (3 / 8 : ℚ)), ("effective_discount", (1 / 2 : ℚ)), ("persistence_high", (3 / 4 : ℚ)), ("persistence_low", (1 / 4 : ℚ))]
    [("gap", [0, 1])]
    [("coverage_increases", false), ("coverage_decreases", true)]
    []
    [])

def gap : List ℚ := expectedRationalVector fixture "gap"
def lowCoverage : ℚ := atOr (discountedGapSum (persistenceKernel (1 / 4 : ℚ)) (1 / 2 : ℚ) 2 gap) 0
def highCoverage : ℚ := atOr (discountedGapSum (persistenceKernel (3 / 4 : ℚ)) (1 / 2 : ℚ) 2 gap) 0
example : lowCoverage = (3 / 8 : ℚ) := by simp [lowCoverage, gap, expectedRationalVector, discountedGapSum, persistenceKernel, matrixVector, dot, addVectors, scaleVector, atOr, fixture] <;> norm_num
example : highCoverage = (1 / 8 : ℚ) := by simp [highCoverage, gap, expectedRationalVector, discountedGapSum, persistenceKernel, matrixVector, dot, addVectors, scaleVector, atOr, fixture] <;> norm_num
example : highCoverage < lowCoverage := by simp [lowCoverage, highCoverage, gap, expectedRationalVector, discountedGapSum, persistenceKernel, matrixVector, dot, addVectors, scaleVector, atOr, fixture] <;> norm_num

end PersistenceDecreasesCoverage

namespace PersistenceIncreasesCoverage

def fixture : ExactFixture :=
  ExactFixture.mk
  "lean-julia-exact-fixture-v2"
  "persistence_increases_coverage"
  "S7 persistence-increases-coverage example"
  ["current", "other"]
  [[0, 1], [1, 0]]
  (1 / 2 : ℚ)
  ["marker"]
  [ExactStrategy.mk "inactive" [0, 0] [], ExactStrategy.mk "candidate" [1, 0] ["marker"]]
  [ExactLibrary.mk "current" ["inactive"]]
  [ExactProject.mk "innovate" [0, 0] 1 1 false [] ["candidate"]]
  (ExactExpected.mk
    [("coverage_high_persistence", (11 / 8 : ℚ)), ("coverage_low_persistence", (9 / 8 : ℚ)), ("effective_discount", (1 / 2 : ℚ)), ("persistence_high", (3 / 4 : ℚ)), ("persistence_low", (1 / 4 : ℚ))]
    [("gap", [1, 0])]
    [("coverage_increases", true), ("coverage_decreases", false)]
    []
    [])

def gap : List ℚ := expectedRationalVector fixture "gap"
def lowCoverage : ℚ := atOr (discountedGapSum (persistenceKernel (1 / 4 : ℚ)) (1 / 2 : ℚ) 2 gap) 0
def highCoverage : ℚ := atOr (discountedGapSum (persistenceKernel (3 / 4 : ℚ)) (1 / 2 : ℚ) 2 gap) 0
example : lowCoverage = (9 / 8 : ℚ) := by simp [lowCoverage, gap, expectedRationalVector, discountedGapSum, persistenceKernel, matrixVector, dot, addVectors, scaleVector, atOr, fixture] <;> norm_num
example : highCoverage = (11 / 8 : ℚ) := by simp [highCoverage, gap, expectedRationalVector, discountedGapSum, persistenceKernel, matrixVector, dot, addVectors, scaleVector, atOr, fixture] <;> norm_num
example : lowCoverage < highCoverage := by simp [lowCoverage, highCoverage, gap, expectedRationalVector, discountedGapSum, persistenceKernel, matrixVector, dot, addVectors, scaleVector, atOr, fixture] <;> norm_num

end PersistenceIncreasesCoverage

namespace RawCompressedTransitionIdentity

def fixture : ExactFixture :=
  ExactFixture.mk
  "lean-julia-exact-fixture-v2"
  "raw_compressed_transition_identity"
  "T1 raw-to-compressed transition identity"
  ["only"]
  [[1]]
  (1 / 2 : ℚ)
  ["key"]
  [ExactStrategy.mk "inactive" [0] [], ExactStrategy.mk "bridge" [0] ["key"], ExactStrategy.mk "candidate" [2] []]
  [ExactLibrary.mk "base" ["inactive", "bridge"], ExactLibrary.mk "candidate_library" ["inactive", "bridge", "candidate"]]
  [ExactProject.mk "innovate" [0] 1 1 false ["key"] ["candidate"]]
  (ExactExpected.mk
    []
    [("compressed_probabilities", [(1 / 2 : ℚ), (1 / 2 : ℚ)]), ("compressed_terminal_frontiers", [0, 2]), ("raw_projected_probabilities", [(1 / 2 : ℚ), (1 / 2 : ℚ)]), ("raw_projected_terminal_frontiers", [0, 2])]
    [("transition_law_equal", true)]
    []
    [])

def rawMasses : List ℚ :=
  expectedRationalVector fixture "raw_projected_probabilities"
def compressedMasses : List ℚ :=
  expectedRationalVector fixture "compressed_probabilities"
def rawFrontiers : List ℚ :=
  expectedRationalVector fixture "raw_projected_terminal_frontiers"
def compressedFrontiers : List ℚ :=
  expectedRationalVector fixture "compressed_terminal_frontiers"
example : rawMasses = [(1 / 2 : ℚ), (1 / 2 : ℚ)] := by simp [rawMasses, expectedRationalVector, fixture] <;> norm_num
example : rawMasses = compressedMasses := by simp [rawMasses, compressedMasses, expectedRationalVector, fixture] <;> norm_num
example : rawFrontiers = compressedFrontiers := by simp [rawFrontiers, compressedFrontiers, expectedRationalVector, fixture] <;> norm_num

end RawCompressedTransitionIdentity

namespace RawCompressedValueEquality

def fixture : ExactFixture :=
  ExactFixture.mk
  "lean-julia-exact-fixture-v2"
  "raw_compressed_value_equality"
  "T1 raw/compressed value equality"
  ["only"]
  [[1]]
  (1 / 2 : ℚ)
  ["key"]
  [ExactStrategy.mk "inactive" [0] [], ExactStrategy.mk "bridge" [0] ["key"], ExactStrategy.mk "candidate" [2] []]
  [ExactLibrary.mk "base" ["inactive", "bridge"], ExactLibrary.mk "candidate_library" ["inactive", "bridge", "candidate"]]
  [ExactProject.mk "innovate" [0] 1 1 false ["key"] ["candidate"]]
  (ExactExpected.mk
    [("compressed_bellman_residual", 0), ("compressed_infinite_value", (4 / 3 : ℚ)), ("raw_bellman_residual", 0), ("raw_infinite_value", (4 / 3 : ℚ))]
    [("compressed_finite_values_horizon_zero_to_five", [0, 0, (1 / 2 : ℚ), (7 / 8 : ℚ), (35 / 32 : ℚ), (155 / 128 : ℚ)]), ("raw_finite_values_horizon_zero_to_five", [0, 0, (1 / 2 : ℚ), (7 / 8 : ℚ), (35 / 32 : ℚ), (155 / 128 : ℚ)])]
    [("finite_values_equal", true), ("infinite_values_equal", true), ("stationary_actions_equal", true)]
    []
    [("compressed_stationary_action", ["research:innovate"]), ("raw_stationary_action", ["research:innovate"])])

def rawFiniteValues : List ℚ :=
  expectedRationalVector fixture "raw_finite_values_horizon_zero_to_five"
def compressedFiniteValues : List ℚ :=
  expectedRationalVector fixture "compressed_finite_values_horizon_zero_to_five"
def rawInfiniteValue : ℚ :=
  expectedRationalScalar fixture "raw_infinite_value"
def compressedInfiniteValue : ℚ :=
  expectedRationalScalar fixture "compressed_infinite_value"
example : rawFiniteValues = compressedFiniteValues := by simp [rawFiniteValues, compressedFiniteValues, expectedRationalVector, fixture] <;> norm_num
example : rawInfiniteValue = compressedInfiniteValue := by simp [rawInfiniteValue, compressedInfiniteValue, expectedRationalScalar, fixture] <;> norm_num
example : expectedRationalScalar fixture "raw_bellman_residual" = 0 := by simp [expectedRationalScalar, fixture] <;> norm_num
example : expectedRationalScalar fixture "compressed_bellman_residual" = 0 := by simp [expectedRationalScalar, fixture] <;> norm_num

end RawCompressedValueEquality

namespace SafeDeletion

def fixture : ExactFixture :=
  ExactFixture.mk
  "lean-julia-exact-fixture-v2"
  "safe_deletion"
  "T3 safe deletion"
  ["low", "high"]
  [[1, 0], [0, 1]]
  (1 / 2 : ℚ)
  ["signal"]
  [ExactStrategy.mk "inactive" [0, 0] [], ExactStrategy.mk "leader" [2, 1] ["signal"], ExactStrategy.mk "duplicate" [1, 1] ["signal"]]
  [ExactLibrary.mk "after" ["inactive", "leader"], ExactLibrary.mk "before" ["inactive", "leader", "duplicate"]]
  [ExactProject.mk "observe" [0, 0] 1 1 false ["signal"] ["leader"]]
  (ExactExpected.mk
    []
    [("frontier_after", [2, 1]), ("frontier_before", [2, 1])]
    [("compressed_state_equal", true), ("generatively_redundant", true), ("operationally_redundant", true)]
    []
    [("modules_after", ["signal"]), ("modules_before", ["signal"])])

example : frontier fixture "before" = [2, 1] := by simp [frontier, frontierAt, libraryStrategies, profileAt, lookupLibrary, lookupStrategy, atOr, fixture] <;> norm_num
example : frontier fixture "after" = [2, 1] := by simp [frontier, frontierAt, libraryStrategies, profileAt, lookupLibrary, lookupStrategy, atOr, fixture] <;> norm_num
example : moduleSupplied fixture "before" "signal" = true := by simp [moduleSupplied, libraryStrategies, strategySupplies, lookupLibrary, lookupStrategy, fixture] <;> norm_num
example : moduleSupplied fixture "after" "signal" = true := by simp [moduleSupplied, libraryStrategies, strategySupplies, lookupLibrary, lookupStrategy, fixture] <;> norm_num
example : frontier fixture "before" = expectedRationalVector fixture "frontier_before" := by simp [expectedRationalVector, frontier, frontierAt, libraryStrategies, profileAt, lookupLibrary, lookupStrategy, atOr, fixture] <;> norm_num

end SafeDeletion

namespace SingleGapResearchRegion

def fixture : ExactFixture :=
  ExactFixture.mk
  "lean-julia-exact-fixture-v2"
  "single_gap_research_region"
  "S5 destructive-kernel compatibility fixture"
  ["left", "middle", "right"]
  [[0, 1, 0], [1, 0, 0], [0, 1, 0]]
  1
  ["marker"]
  [ExactStrategy.mk "inactive" [0, 0, 0] [], ExactStrategy.mk "candidate" [0, 1, 0] ["marker"]]
  [ExactLibrary.mk "current" ["inactive"]]
  [ExactProject.mk "innovate" [(1 / 2 : ℚ), (1 / 2 : ℚ), (1 / 2 : ℚ)] 1 1 false [] ["candidate"]]
  (ExactExpected.mk
    [("connected_components", 2)]
    [("candidate_gap", [0, 1, 0]), ("coverage_potential", [1, 0, 1])]
    [("kernel_stochastically_monotone", false), ("region_disconnected", true)]
    [("research_region", [true, false, true])]
    [])

example : projectGap fixture "current" "innovate" = [0, 1, 0] := by simp [projectGap, projectGapAt, candidateGapAt, frontierAt, libraryStrategies, profileAt, lookupProject, lookupLibrary, lookupStrategy, atOr, fixture] <;> norm_num
example : grossCoverage fixture "current" "innovate" = [1, 0, 1] := by simp [grossCoverage, projectGap, projectGapAt, candidateGapAt, frontierAt, libraryStrategies, profileAt, lookupProject, lookupLibrary, lookupStrategy, matrixVector, dot, scaleVector, atOr, fixture] <;> norm_num
example : researchRegion fixture "current" "innovate" = [true, false, true] := by simp [researchRegion, weakRegion, grossCoverage, projectGap, projectGapAt, candidateGapAt, frontierAt, libraryStrategies, profileAt, lookupProject, lookupLibrary, lookupStrategy, matrixVector, dot, scaleVector, atOr, fixture] <;> norm_num
example : componentCount (researchRegion fixture "current" "innovate") = 2 := by simp [componentCount, componentCountAux, researchRegion, weakRegion, grossCoverage, projectGap, projectGapAt, candidateGapAt, frontierAt, libraryStrategies, profileAt, lookupProject, lookupLibrary, lookupStrategy, matrixVector, dot, scaleVector, atOr, fixture] <;> norm_num
example : researchRegion fixture "current" "innovate" = expectedBooleanVector fixture "research_region" := by simp [expectedBooleanVector, researchRegion, weakRegion, grossCoverage, projectGap, projectGapAt, candidateGapAt, frontierAt, libraryStrategies, profileAt, lookupProject, lookupLibrary, lookupStrategy, matrixVector, dot, scaleVector, atOr, fixture] <;> norm_num

end SingleGapResearchRegion

namespace StrategyInnovationEquation

def fixture : ExactFixture :=
  ExactFixture.mk
  "lean-julia-exact-fixture-v2"
  "strategy_innovation_equation"
  "S4 Strategy Innovation Equation compatibility fixture"
  ["current", "future"]
  [[0, 1], [0, 1]]
  (1 / 2 : ℚ)
  ["marker"]
  [ExactStrategy.mk "inactive" [0, 0] [], ExactStrategy.mk "candidate" [1, 2] ["marker"]]
  [ExactLibrary.mk "current" ["inactive"]]
  [ExactProject.mk "innovate" [0, 0] 1 1 false [] ["candidate"]]
  (ExactExpected.mk
    [("initial_innovation_value", (5 / 2 : ℚ))]
    [("candidate_gap", [1, 2]), ("discounted_gap_sum_horizon_three", [(5 / 2 : ℚ), (7 / 2 : ℚ)])]
    [("innovation_equation_identity", true)]
    []
    [])

def gap : List ℚ := candidateGap fixture "current" "candidate"
def innovationValue : List ℚ := discountedGapSum fixture.transitionRows fixture.discount 3 gap
example : gap = [1, 2] := by simp [gap, candidateGap, candidateGapAt, frontierAt, libraryStrategies, profileAt, lookupLibrary, lookupStrategy, atOr, fixture] <;> norm_num
example : innovationValue = [(5 / 2 : ℚ), (7 / 2 : ℚ)] := by simp [innovationValue, discountedGapSum, gap, candidateGap, candidateGapAt, frontierAt, libraryStrategies, profileAt, lookupLibrary, lookupStrategy, matrixVector, dot, addVectors, scaleVector, atOr, fixture] <;> norm_num
example : atOr innovationValue 0 = (5 / 2 : ℚ) := by simp [innovationValue, discountedGapSum, gap, candidateGap, candidateGapAt, frontierAt, libraryStrategies, profileAt, lookupLibrary, lookupStrategy, matrixVector, dot, addVectors, scaleVector, atOr, fixture] <;> norm_num
example : innovationValue = expectedRationalVector fixture "discounted_gap_sum_horizon_three" := by simp [expectedRationalVector, innovationValue, discountedGapSum, gap, candidateGap, candidateGapAt, frontierAt, libraryStrategies, profileAt, lookupLibrary, lookupStrategy, matrixVector, dot, addVectors, scaleVector, atOr, fixture] <;> norm_num

end StrategyInnovationEquation

end StrategyInnovation.Fixtures.Generated
