import StrategyInnovation.Optimization.TaggedCoverPreprocessing
import Mathlib.Tactic.FinCases
import Mathlib.Tactic.NormNum

/-!
# Generated exact journal evidence fixtures

Generated by `julia/scripts/export_journal_evidence_fixtures.jl` from the
same exact Julia values as `journal_formal_evidence_v1.toml`. These theorems
check only the displayed finite arithmetic and coverage instances. They do
not formalize a universal complexity, preprocessing-optimality,
dynamic-programming, approximation, or implementation theorem.
-/

namespace StrategyInnovation

namespace Fixtures

namespace JournalAlgorithms

def gapK : ℕ := 4
def gapEpsilon : ℚ := 1 / 2
def gapHeuristicBurden : ℚ := 4
def gapOptimumBurden : ℚ := 1 + gapEpsilon

/-- The shared `k=4`, `epsilon=1/2` deletion-gap fixture has ratio `8/3`. -/
theorem gap_k4_half_ratio_exact :
    gapHeuristicBurden / gapOptimumBurden = (8 : ℚ) / 3 := by
  norm_num [gapHeuristicBurden, gapOptimumBurden, gapEpsilon]

def maskOr : List Bool → List Bool → List Bool
  | left :: lefts, right :: rights => (left || right) :: maskOr lefts rights
  | _, _ => []

/-- The shared DP take transition forms full coverage by exact mask union. -/
theorem requirementMask_take_union_exact :
    maskOr [true, false, true] [false, true, false] = [true, true, true] := by
  decide

def preprocessingCoverage : Fin 3 → Finset (Fin 3)
  | 0 => {0}
  | 1 => {1, 2}
  | 2 => {2}

def preprocessingRequirements : Finset (Fin 3) := Finset.univ

/-- Requirement zero has strategy zero as its unique carrier in the shared fixture. -/
theorem preprocessing_unique_first_carrier
    (strategy : Fin 3)
    (hcarrier : (0 : Fin 3) ∈ preprocessingCoverage strategy) :
    strategy = 0 := by
  fin_cases strategy <;> simp [preprocessingCoverage] at hcarrier ⊢

/-- Every cover of the shared fixture selects its unique first carrier. -/
theorem preprocessing_fixture_forces_first
    (selected : Finset (Fin 3))
    (hcover :
      Optimization.TaggedCoverPreprocessing.SelectedCovers
        preprocessingCoverage preprocessingRequirements selected) :
    (0 : Fin 3) ∈ selected := by
  exact Optimization.TaggedCoverPreprocessing.uniqueCarrier_mem_of_selectedCovers
    preprocessingCoverage preprocessingRequirements selected
    (by simp [preprocessingRequirements]) preprocessing_unique_first_carrier hcover

def greedySingletonBurden : ℚ := 1 + 1 / 2 + 1 / 3
def greedyBundleBurden : ℚ := 1 + 1 / 12

/-- Exact arithmetic for the shared three-row Chvatal near-tight fixture. -/
theorem greedy_three_row_ratio_exact :
    greedySingletonBurden / greedyBundleBurden = (22 : ℚ) / 13 := by
  norm_num [greedySingletonBurden, greedyBundleBurden]

end JournalAlgorithms

end Fixtures

end StrategyInnovation
