import Mathlib.Data.Fin.VecNotation
import Mathlib.Data.Rat.Defs

namespace StrategyInnovation.Fixtures.MultiGapRegion

/- Exact data generated by julia/scripts/search_multi_gap_topology.jl.
Proofs belong in StrategyInnovation.Counterexamples.MultiGapRegion. -/

def leftCandidateGap : Fin 5 → ℚ := ![4, 0, 0, 0, 0]

def rightCandidateGap : Fin 5 → ℚ := ![0, 0, 0, 0, 4]

def bernsteinKernel : Fin 5 → Fin 5 → ℚ :=
  ![![1, 0, 0, 0, 0], ![(81 / 256 : ℚ), (27 / 64 : ℚ), (27 / 128 : ℚ), (3 / 64 : ℚ), (1 / 256 : ℚ)], ![(1 / 16 : ℚ), (1 / 4 : ℚ), (3 / 8 : ℚ), (1 / 4 : ℚ), (1 / 16 : ℚ)], ![(1 / 256 : ℚ), (3 / 64 : ℚ), (27 / 128 : ℚ), (27 / 64 : ℚ), (81 / 256 : ℚ)], ![0, 0, 0, 0, 1]]

def researchCost : Fin 5 → ℚ := ![1, 1, 1, 1, 1]

def expectedPotential : Fin 5 → ℚ := ![4, (41 / 32 : ℚ), (1 / 2 : ℚ), (41 / 32 : ℚ), 4]

def topologyConstantGap : Fin 5 → ℚ := ![2, 2, 2, 2, 2]

def topologyVariableCost : Fin 5 → ℚ := ![0, 3, 0, 3, 0]

end StrategyInnovation.Fixtures.MultiGapRegion
