import Mathlib.Data.Fin.VecNotation
import Mathlib.Data.Rat.Defs

namespace StrategyInnovation.Fixtures.SingleGapGeometry

/- This exact data-only fixture is generated by
`julia/scripts/search_single_gap_geometry.jl`. Proofs belong in
`StrategyInnovation.Coverage.SingleGap`. -/

def peakedGap : Fin 3 → ℚ := ![0, 1, 0]

def destructiveKernel : Fin 3 → Fin 3 → ℚ :=
  ![![0, 1, 0], ![1, 0, 0], ![0, 1, 0]]

def disconnectedPotential : Fin 3 → ℚ := ![1, 0, 1]

def increasingPotential : Fin 3 → ℚ := ![1, 2, 3]

def disconnectedCost : Fin 3 → ℚ := ![0, 3, 0]

end StrategyInnovation.Fixtures.SingleGapGeometry
