module AoRManuscriptEvidenceInputs

using Printf
using SHA: sha256
using TOML

const REPOSITORY_ROOT = normpath(joinpath(@__DIR__, "..", ".."))
const ALGORITHM_TABLE_ROOT = joinpath(REPOSITORY_ROOT, "journal", "aor", "tables")
const FINANCIAL_ROOT = joinpath(REPOSITORY_ROOT, "experiments", "results", "summaries")
const OUTPUT_ROOT = joinpath(REPOSITORY_ROOT, "journal", "aor", "manuscript", "tables")
const RESOURCE_OUTPUT_ROOT = joinpath(REPOSITORY_ROOT, "journal", "aor", "online_resource", "tables")
const POINT_IN_TIME_ROOT = joinpath(
    REPOSITORY_ROOT,
    "experiments",
    "financial_strategy_library_panel_v3",
)
const CLOSURE_OPTION_ROOT = joinpath(
    REPOSITORY_ROOT,
    "experiments",
    "financial_strategy_library_panel_v4",
)

const OUTPUTS = Dict(
    "macros" => joinpath(OUTPUT_ROOT, "evidence_macros.tex"),
    "resource_macros" => joinpath(RESOURCE_OUTPUT_ROOT, "evidence_macros.tex"),
    "scaling" => joinpath(OUTPUT_ROOT, "computational_scaling_compact.tex"),
    "heuristics" => joinpath(OUTPUT_ROOT, "heuristic_quality_compact.tex"),
    "preprocessing" => joinpath(OUTPUT_ROOT, "preprocessing_multistart_compact.tex"),
    "adversarial" => joinpath(OUTPUT_ROOT, "adversarial_gap_compact.tex"),
    "financial_instances" => joinpath(OUTPUT_ROOT, "financial_instance_summary.tex"),
    "financial_algorithms" => joinpath(OUTPUT_ROOT, "financial_algorithm_burdens.tex"),
    "financial_robustness" => joinpath(OUTPUT_ROOT, "financial_robustness_summary.tex"),
    "point_in_time_study" => joinpath(OUTPUT_ROOT, "point_in_time_portfolio_library_study.tex"),
    "closure_option_experiment" => joinpath(OUTPUT_ROOT, "closure_option_mechanism_experiment.tex"),
    "resource_point_in_time_study" => joinpath(RESOURCE_OUTPUT_ROOT, "point_in_time_portfolio_library_study.tex"),
    "resource_closure_option_experiment" => joinpath(RESOURCE_OUTPUT_ROOT, "closure_option_mechanism_experiment.tex"),
    "resource_point_in_time_origins" => joinpath(RESOURCE_OUTPUT_ROOT, "point_in_time_origin_results.tex"),
)

sha256_file(path::AbstractString) = bytes2hex(sha256(read(path)))

function split_csv_line(line::AbstractString)
    fields = String[]
    field = IOBuffer()
    quoted = false
    index = firstindex(line)
    while index <= lastindex(line)
        character = line[index]
        if character == '"'
            next_index = nextind(line, index)
            if quoted && next_index <= lastindex(line) && line[next_index] == '"'
                print(field, '"')
                index = next_index
            else
                quoted = !quoted
            end
        elseif character == ',' && !quoted
            push!(fields, String(take!(field)))
        else
            print(field, character)
        end
        index = nextind(line, index)
    end
    quoted && error("unterminated quoted CSV field")
    push!(fields, String(take!(field)))
    return fields
end

function read_csv(path::AbstractString)
    lines = readlines(path)
    isempty(lines) && error("empty CSV: $path")
    header = split_csv_line(first(lines))
    length(unique(header)) == length(header) || error("duplicate CSV header: $path")
    rows = Dict{String,String}[]
    for line in Iterators.drop(lines, 1)
        isempty(strip(line)) && continue
        fields = split_csv_line(line)
        length(fields) == length(header) || error("malformed CSV row: $path")
        push!(rows, Dict(header .=> fields))
    end
    return rows
end

function only_row(rows; filters...)
    selected = filter(rows) do row
        all(row[string(key)] == string(value) for (key, value) in filters)
    end
    length(selected) == 1 || error("expected one row for $(filters), got $(length(selected))")
    return only(selected)
end

function exact(value::AbstractString)
    parts = split(value, "//")
    length(parts) == 1 && return parse(BigInt, only(parts)) // BigInt(1)
    length(parts) == 2 || error("invalid exact rational: $value")
    return parse(BigInt, parts[1]) // parse(BigInt, parts[2])
end

function tex_exact(value::AbstractString)
    rational = exact(value)
    denominator(rational) == 1 && return string(numerator(rational))
    return "\\frac{$(numerator(rational))}{$(denominator(rational))}"
end

function compact_number(value::AbstractString)
    value in ("", "UNAVAILABLE") && return "--"
    parsed = parse(Float64, value)
    return @sprintf("%.4g", parsed)
end

tex_bool(value::AbstractString) = value == "true" ? "yes" : value == "false" ? "no" : error("invalid bool: $value")

function source_comment(paths...)
    return "% Generated by julia/scripts/build_aor_manuscript_evidence_inputs.jl.\n" *
           "% Committed machine sources: $(join(paths, "; ")).\n"
end

function audit_inputs()
    audit_path = joinpath(
        REPOSITORY_ROOT,
        "experiments",
        "algorithmic_compression_v2",
        "results",
        "audit",
        "audit_summary.toml",
    )
    audit = TOML.parsefile(audit_path)
    audit["passed"] === true || error("v2 algorithm audit did not pass")
    audit["error_count"] == 0 || error("v2 algorithm audit contains errors")
    audit["terminal_run_count"] == audit["expected_run_count"] ||
        error("v2 terminal matrix is incomplete")

    registry_path = joinpath(
        REPOSITORY_ROOT,
        "experiments",
        "algorithmic_compression_v2",
        "registry",
        "INSTANCE_REGISTRY.csv",
    )
    registry = read_csv(registry_path)
    final_rows = filter(row -> row["analysis_included"] == "true", registry)
    family_counts = Dict(
        family => count(row -> row["family"] == family, final_rows)
        for family in ("small_exact", "structured", "adversarial")
    )
    length(final_rows) == 173 || error("unexpected v2 analysis population")
    family_counts == Dict("small_exact" => 24, "structured" => 128, "adversarial" => 21) ||
        error("unexpected v2 family counts")

    environment_path = joinpath(
        REPOSITORY_ROOT,
        "experiments",
        "algorithmic_compression_v2",
        "results",
        "environment_amendment_002.toml",
    )
    environment = TOML.parsefile(environment_path)
    environment["julia_version"] == "1.12.6" || error("unexpected Julia version")
    environment["process_concurrency"] == 8 || error("unexpected worker concurrency")
    environment["worker_julia_threads"] == 1 || error("unexpected worker thread count")
    environment["highs_threads"] == 1 || error("unexpected HiGHS thread count")

    v1_notice_path = joinpath(
        REPOSITORY_ROOT,
        "experiments",
        "algorithmic_compression_v1",
        "INCOMPLETE_EXECUTION_NOTICE.md",
    )
    v1_notice = read(v1_notice_path, String)
    v1_match = match(
        r"after\s+([0-9,]+) of ([0-9,]+) registered run records had become terminal and ([0-9,]+) of ([0-9,]+) final\s+instances had been generated",
        v1_notice,
    )
    v1_match === nothing && error("could not parse v1 incomplete-execution notice")
    v1_counts = parse.(Int, replace.(collect(v1_match.captures), "," => ""))
    v1_counts == [1634, 3907, 68, 173] || error("unexpected v1 incomplete-execution counts")

    terminal_financial_path = joinpath(
        REPOSITORY_ROOT,
        "experiments",
        "configs",
        "financial_terminal_audit.toml",
    )
    annual_financial_path = joinpath(
        REPOSITORY_ROOT,
        "experiments",
        "configs",
        "financial_annual_walkforward_audit.toml",
    )
    terminal_financial = TOML.parsefile(terminal_financial_path)["backtest"]
    annual_financial = TOML.parsefile(annual_financial_path)["backtest"]
    for key in ("annualization_sessions", "one_way_transaction_cost_bps", "risk_aversion", "cost_sensitivity_bps")
        terminal_financial[key] == annual_financial[key] || error("financial config mismatch: $key")
    end
    terminal_financial["annualization_sessions"] == 252 || error("unexpected financial annualization")
    terminal_financial["one_way_transaction_cost_bps"] == 5.0 || error("unexpected primary transaction cost")
    terminal_financial["risk_aversion"] == 3.0 || error("unexpected financial risk-aversion index")
    terminal_financial["cost_sensitivity_bps"] == [1.0, 5.0, 10.0] || error("unexpected cost sensitivity grid")
    terminal_financial["frontier_tolerance"] == 1.0e-12 || error("unexpected terminal frontier tolerance")
    annual_financial["frontier_tolerance"] == 1.0e-10 || error("unexpected annual frontier tolerance")

    return (; audit, family_counts, environment, v1_counts, terminal_financial, annual_financial)
end

function macros_source(inputs)
    audit = inputs.audit
    counts = inputs.family_counts
    environment = inputs.environment
    v1_counts = inputs.v1_counts
    financial = inputs.terminal_financial
    status = audit["status_counts"]
    multistart = read_csv(joinpath(ALGORITHM_TABLE_ROOT, "multistart_summary.csv"))
    multistart_complete = sum(parse(Int, row["complete_32_start_n"]) for row in multistart)
    multistart_improved = sum(parse(Int, row["improved_n"]) for row in multistart)
    multistart_complete == 143 || error("unexpected multistart complete count")
    multistart_improved == 96 || error("unexpected multistart improvement count")
    quality = read_csv(joinpath(ALGORITHM_TABLE_ROOT, "heuristic_quality.csv"))
    structured_reference = only_row(
        quality;
        family = "structured",
        reference_class = "MIP_OPTIMAL_EXACTLY_RECHECKED",
        algorithm_id = "weighted_greedy",
    )
    structured_reference["reference_available_n"] == "111" ||
        error("unexpected structured reference count")
    preprocessing = read_csv(joinpath(ALGORITHM_TABLE_ROOT, "preprocessing_reductions.csv"))
    generation_failed_instances = count(
        row -> row["full_status"] == "GENERATION_FAILED" &&
               row["mandatory_status"] == "GENERATION_FAILED",
        preprocessing,
    )
    generation_failed_instances == 16 ||
        error("unexpected generation-failed instance count")
    return source_comment(
        "experiments/algorithmic_compression_v2/results/audit/audit_summary.toml",
        "experiments/algorithmic_compression_v2/registry/INSTANCE_REGISTRY.csv",
        "experiments/algorithmic_compression_v2/results/environment_amendment_002.toml",
        "journal/aor/tables/heuristic_quality.csv",
        "journal/aor/tables/multistart_summary.csv",
        "journal/aor/tables/preprocessing_reductions.csv",
        "experiments/algorithmic_compression_v1/INCOMPLETE_EXECUTION_NOTICE.md",
        "experiments/configs/financial_terminal_audit.toml",
        "experiments/configs/financial_annual_walkforward_audit.toml",
    ) * """
\\newcommand{\\AORBenchmarkInstances}{$(sum(values(counts)))}
\\newcommand{\\AORBenchmarkSmallExact}{$(counts["small_exact"])}
\\newcommand{\\AORBenchmarkStructured}{$(counts["structured"])}
\\newcommand{\\AORBenchmarkAdversarial}{$(counts["adversarial"])}
\\newcommand{\\AORBenchmarkRuns}{$(audit["terminal_run_count"])}
\\newcommand{\\AORBenchmarkAccepted}{$(audit["accepted_solution_count"])}
\\newcommand{\\AORBenchmarkUnsuccessful}{$(audit["unsuccessful_run_count"])}
\\newcommand{\\AORExactCapable}{$(audit["exact_instance_count"])}
\\newcommand{\\AORExactAgreement}{$(audit["exact_agreement_count"])}
\\newcommand{\\AORExactUnavailable}{$(audit["exact_agreement_unavailable_count"])}
\\newcommand{\\AOROptimizerIdentityDifferences}{$(audit["optimizer_identity_difference_count"])}
\\newcommand{\\AORGenerationFailed}{$(status["GENERATION_FAILED"])}
\\newcommand{\\AORGenerationFailedInstances}{$generation_failed_instances}
\\newcommand{\\AORImplementationErrors}{$(status["IMPLEMENTATION_ERROR"])}
\\newcommand{\\AORMemoryLimited}{$(status["MEMORY_LIMIT"])}
\\newcommand{\\AORStructuredReferences}{$(structured_reference["reference_available_n"])}
\\newcommand{\\AORMultistartComplete}{$multistart_complete}
\\newcommand{\\AORMultistartImproved}{$multistart_improved}
\\newcommand{\\AORJuliaVersion}{$(environment["julia_version"])}
\\newcommand{\\AORHiGHSVersion}{$(environment["highs_version"])}
\\newcommand{\\AORWorkerCount}{$(environment["process_concurrency"])}
\\newcommand{\\AORCPU}{$(environment["cpu"])}
\\newcommand{\\AORVOneTerminalRuns}{$(v1_counts[1])}
\\newcommand{\\AORVOneRegisteredRuns}{$(v1_counts[2])}
\\newcommand{\\AORVOneGeneratedInstances}{$(v1_counts[3])}
\\newcommand{\\AORVOneRegisteredInstances}{$(v1_counts[4])}
\\newcommand{\\AORFinancialAnnualization}{$(financial["annualization_sessions"])}
\\newcommand{\\AORFinancialRiskAversion}{$(Int(financial["risk_aversion"]))}
\\newcommand{\\AORFinancialPrimaryCostBps}{$(Int(financial["one_way_transaction_cost_bps"]))}
\\newcommand{\\AORFinancialSensitivityBps}{1, 5, and 10}
\\newcommand{\\AORTerminalFrontierTolerance}{10^{-12}}
\\newcommand{\\AORAnnualFrontierTolerance}{10^{-10}}
"""
end

function scaling_source()
    path = joinpath(ALGORITHM_TABLE_ROOT, "computational_scaling.csv")
    rows = read_csv(path)
    io = IOBuffer()
    print(io, source_comment("journal/aor/tables/computational_scaling.csv"))
    println(io, "\\begin{table}[tbp]")
    println(io, "\\centering\\scriptsize")
    println(io, "\\setlength{\\tabcolsep}{3.4pt}")
    println(io, "\\resizebox{\\textwidth}{!}{%")
    println(io, "\\begin{tabular}{@{}lrrrcrr@{}}")
    println(io, "\\toprule")
    println(io, "Size & Enum. solved & Enum. median s & DP solved & DP median states & MIP solved & MIP median s \\\\")
    println(io, "\\midrule")
    for size in ("N7-R6", "N7-R10", "N11-R6", "N11-R10", "N15-R6", "N15-R10")
        enumeration = only_row(rows; family = "small_exact", size, algorithm_id = "complete_enumeration", preprocessing_variant = "mandatory_only")
        dp = only_row(rows; family = "small_exact", size, algorithm_id = "requirement_mask_dp", preprocessing_variant = "mandatory_only")
        mip = only_row(rows; family = "small_exact", size, algorithm_id = "jump_highs_tagged_cover", preprocessing_variant = "full_fixed_point")
        println(io,
            "$size & $(enumeration["solved_n"])/$(enumeration["registered_n"]) & $(compact_number(enumeration["wall_seconds_median_solved"])) & " *
            "$(dp["solved_n"])/$(dp["registered_n"]) & $(compact_number(dp["dp_states_median"])) & " *
            "$(mip["solved_n"])/$(mip["registered_n"]) & $(compact_number(mip["wall_seconds_median_solved"])) \\\\",
        )
    end
    println(io, "\\midrule")
    println(io, "Structured size & MIP solved & MIP median s & MIP median PAR--2 s & node records & median nodes & limit s \\\\")
    println(io, "\\midrule")
    for size in ("N64-R32", "N64-R64", "N192-R32", "N192-R64")
        mip = only_row(rows; family = "structured", size, algorithm_id = "jump_highs_tagged_cover", preprocessing_variant = "full_fixed_point")
        println(io,
            "$size & $(mip["solved_n"])/$(mip["registered_n"]) & $(compact_number(mip["wall_seconds_median_solved"])) & " *
            "$(compact_number(mip["par2_median_seconds"])) & $(mip["mip_nodes_available_n"]) & " *
            "$(compact_number(mip["mip_nodes_median"])) & $(compact_number(mip["time_limit_seconds"])) \\\\",
        )
    end
    println(io, "\\bottomrule")
    println(io, "\\end{tabular}")
    println(io, "}")
    println(io, "\\caption{Registered synthetic scaling evidence. The upper panel uses exact-capable Family A instances; the lower panel uses the full-fixed-point HiGHS variant on structured Family B. Solved fractions keep failed rows in their denominators. State and node entries are medians only over records exposing those diagnostics; a dash is unavailable, not zero. PAR--2 assigns twice the registered limit to an unsuccessful run. Runtime includes fixed eight-worker contention and is neither proof nor a cross-machine benchmark.}")
    println(io, "\\label{tab:aor-computational-scaling-compact}")
    println(io, "\\end{table}")
    return String(take!(io))
end

function heuristic_source()
    path = joinpath(ALGORITHM_TABLE_ROOT, "heuristic_quality.csv")
    rows = read_csv(path)
    algorithm_order = (
        "weighted_greedy",
        "cardinality_greedy",
        "weighted_greedy_reverse_delete",
        "heaviest_safe_first",
        "lightest_safe_first",
        "maximum_immediate_burden_release",
        "minimum_unique_carrier_exposure",
        "declared_source_order",
        "random_order_rechecked_deletion",
        "multistart_random_rechecked_deletion_32",
    )
    io = IOBuffer()
    print(io, source_comment("journal/aor/tables/heuristic_quality.csv"))
    println(io, "\\begin{table}[tbp]")
    println(io, "\\centering\\scriptsize")
    println(io, "\\setlength{\\tabcolsep}{4.0pt}")
    println(io, "\\resizebox{\\textwidth}{!}{%")
    println(io, "\\begin{tabular}{@{}lrrrrr@{}}")
    println(io, "\\toprule")
    println(io, "Algorithm & Attained/reference & Mean gap & Median & q90 & Worst \\\\")
    for (family, reference, heading) in (
        ("small_exact", "EXACT_FINITE", "Family A: exact finite reference"),
        ("structured", "MIP_OPTIMAL_EXACTLY_RECHECKED", "Family B: HiGHS-\\texttt{OPTIMAL}, exactly rechecked reference"),
    )
        println(io, "\\midrule")
        println(io, "\\multicolumn{6}{@{}l}{\\textit{$heading}}\\\\")
        for algorithm_id in algorithm_order
            row = only_row(rows; family, reference_class = reference, algorithm_id)
            println(io,
                "$(row["algorithm"]) & $(row["attained_n"])/$(row["attainment_denominator"]) & " *
                "$(compact_number(row["relative_gap_mean"])) & $(compact_number(row["relative_gap_median"])) & " *
                "$(compact_number(row["relative_gap_q90"])) & $(compact_number(row["relative_gap_worst"])) \\\\",
            )
        end
    end
    println(io, "\\bottomrule")
    println(io, "\\end{tabular}")
    println(io, "}")
    println(io, "\\caption{Registered heuristic burden quality. Relative gap is \\( (W-W^\\star)/W^\\star \\). Attainment denominators include every registered row with an available reference; gap moments use exactly feasible returned libraries. Family A and Family B have different reference evidence and are deliberately not pooled.}")
    println(io, "\\label{tab:aor-heuristic-quality-compact}")
    println(io, "\\end{table}")
    return String(take!(io))
end

function preprocessing_source()
    preprocessing = read_csv(joinpath(ALGORITHM_TABLE_ROOT, "preprocessing_summary.csv"))
    multistart = read_csv(joinpath(ALGORITHM_TABLE_ROOT, "multistart_summary.csv"))
    io = IOBuffer()
    print(io, source_comment(
        "journal/aor/tables/preprocessing_summary.csv",
        "journal/aor/tables/multistart_summary.csv",
    ))
    println(io, "\\begin{table}[tbp]")
    println(io, "\\centering\\scriptsize")
    println(io, "\\setlength{\\tabcolsep}{3.5pt}")
    println(io, "\\resizebox{\\textwidth}{!}{%")
    println(io, "\\begin{tabular}{@{}lrrrrrr@{}}")
    println(io, "\\toprule")
    println(io, "Size & Preprocess n & Median var. red. & Median row red. & Median log PAR--2 ratio & 32-start complete & Improved \\\\")
    println(io, "\\midrule")
    for size in ("N64-R32", "N64-R64", "N192-R32", "N192-R64")
        pre = only_row(preprocessing; family = "structured", size)
        multi = only_row(multistart; family = "structured", size)
        println(io,
            "$size & $(pre["preprocessing_available_n"])/$(pre["registered_n"]) & " *
            "$(compact_number(pre["variable_reduction_median"])) & $(compact_number(pre["requirement_reduction_median"])) & " *
            "$(compact_number(pre["median_log_par2_difference"])) & $(multi["complete_32_start_n"])/$(multi["registered_n"]) & " *
            "$(multi["improved_n"])/$(multi["improvement_denominator"]) \\\\",
        )
    end
    println(io, "\\bottomrule")
    println(io, "\\end{tabular}")
    println(io, "}")
    println(io, "\\caption{Registered preprocessing and multi-start evidence on structured instances. Reductions are shares removed. The log ratio is \\(\\log(\\mathrm{PAR2}_{\\rm full}/\\mathrm{PAR2}_{\\rm mandatory})\\), so a positive value favors the mandatory-only pipeline in elapsed penalized runtime despite the model-size reduction. Unavailable multi-start endpoints are not coded as zero improvement.}")
    println(io, "\\label{tab:aor-preprocessing-multistart}")
    println(io, "\\end{table}")
    return String(take!(io))
end

function adversarial_source()
    rows = read_csv(joinpath(ALGORITHM_TABLE_ROOT, "adversarial_family.csv"))
    selected = filter(rows) do row
        row["mechanism"] == "unbounded_heaviest_safe_first_gap" &&
            row["algorithm_id"] == "heaviest_safe_first"
    end
    length(selected) == 3 || error("adversarial gap family must have three scales")
    scale_order = Dict("small" => 1, "medium" => 2, "large" => 3)
    sort!(selected; by = row -> scale_order[row["scale"]])
    io = IOBuffer()
    print(io, source_comment("journal/aor/tables/adversarial_family.csv"))
    println(io, "\\begin{table}[tbp]")
    println(io, "\\centering\\small")
    println(io, "\\resizebox{\\textwidth}{!}{%")
    println(io, "\\begin{tabular}{@{}lllll@{}}")
    println(io, "\\toprule")
    println(io, "Scale & Parameter & Reference evidence & Observed ratio & Theoretical ratio \\\\")
    println(io, "\\midrule")
    for row in selected
        parts = split(row["mechanism_parameter"], ';')
        length(parts) == 2 || error("unexpected adversarial parameter")
        k_value = split(parts[1], '=')[2]
        epsilon_value = split(parts[2], '=')[2]
        parameter = "k=$k_value,\\ \\epsilon=$(tex_exact(epsilon_value))"
        evidence = row["reference_class"] == "EXACT_FINITE" ? "exact finite" : "HiGHS-\\texttt{OPTIMAL}, rechecked"
        println(io,
            "$(row["scale"]) & \\($parameter\\) & $evidence & " *
            "\\($(tex_exact(row["observed_burden_ratio"]))\\) & \\($(tex_exact(row["theoretical_ratio_if_applicable"]))\\) \\\\",
        )
    end
    println(io, "\\bottomrule")
    println(io, "\\end{tabular}")
    println(io, "}")
    println(io, "\\caption{Registered adversarial instances for heaviest-safe-first. Equality between observed and theoretical ratios is a synthetic fixture check of the human-proved family, not an empirical approximation guarantee.}")
    println(io, "\\label{tab:aor-adversarial-gap}")
    println(io, "\\end{table}")
    return String(take!(io))
end

function financial_inputs()
    comparison_path = joinpath(FINANCIAL_ROOT, "financial_algorithm_comparison_v1.csv")
    robustness_path = joinpath(
        FINANCIAL_ROOT,
        "financial_resource_optimization_weight_robustness_summary.csv",
    )
    certificate_path = joinpath(
        FINANCIAL_ROOT,
        "financial_resource_optimization_weight_robustness_empty_residual_certificates.csv",
    )
    comparison = read_csv(comparison_path)
    robustness = read_csv(robustness_path)
    certificates = read_csv(certificate_path)

    all(row["exact_feasible"] == "true" for row in robustness if !isempty(row["selected_exact_burden"])) ||
        error("financial robustness contains an uncertified returned endpoint")
    length(certificates) == 6 || error("expected six financial empty-residual certificates")
    all(
        row["preprocessing_feasible"] == "true" &&
        row["residual_strategy_count"] == "0" &&
        row["residual_requirement_count"] == "0" &&
        row["certified_global_optimum"] == "true" &&
        row["solver_invoked"] == "false" &&
        row["lean_verified"] == "false"
        for row in certificates
    ) || error("financial empty-residual certificate drift")
    return (; comparison, robustness, certificates)
end

function financial_instance_source(inputs)
    rows = inputs.comparison
    io = IOBuffer()
    print(io, source_comment("experiments/results/summaries/financial_algorithm_comparison_v1.csv"))
    println(io, "\\begin{center}")
    println(io, "\\begin{minipage}{\\textwidth}")
    println(io, "\\centering\\scriptsize")
    println(io, "\\setlength{\\tabcolsep}{3.2pt}")
    println(io, "\\resizebox{\\textwidth}{!}{%")
    println(io, "\\begin{tabular}{@{}lrrrrrrrrr@{}}")
    println(io, "\\toprule")
    println(io, "Audit & Active & Frontier & Modules & Density & Unique & Forced & Vars & Rows & Residual \\\\")
    println(io, "\\midrule")
    for (audit_id, label) in (("locked_terminal_v1", "Terminal"), ("annual_walk_forward_v2", "Annual"))
        row = only_row(rows; audit_id, schedule_id = "uniform_cardinality", algorithm_id = "current_stepwise_safe_deletion")
        println(io,
            "$label & $(row["active_strategy_count"]) & $(row["frontier_requirement_count"]) & " *
            "$(row["module_requirement_count"]) & \\($(tex_exact(row["coverage_density"]))\\) & " *
            "$(row["unique_carrier_count"]) & $(row["forced_strategy_count"]) & " *
            "$(row["variables_before_preprocessing"])\\(\\to\\)$(row["variables_after_preprocessing"]) & " *
            "$(row["constraints_before_preprocessing"])\\(\\to\\)$(row["constraints_after_preprocessing"]) & empty \\\\",
        )
    end
    println(io, "\\bottomrule")
    println(io, "\\end{tabular}")
    println(io, "}")
    println(io, "\\captionof{table}{Public-safe source-instance structure and exact fixed-point preprocessing. Active counts exclude the mandatory inactive entry; binary-variable counts include it. Density is exact active strategy--requirement incidence. Duplicate coverage and dominance removals are zero in both sources. ``Empty'' is an exact finite preprocessing certificate under the human-proved rules, followed by original-instance rechecks; it is neither Lean nor solver proof.}")
    println(io, "\\label{tab:aor-financial-instances}")
    println(io, "\\end{minipage}")
    println(io, "\\end{center}")
    return String(take!(io))
end

function financial_algorithm_source(inputs)
    rows = inputs.robustness
    algorithms = (
        ("current_stepwise_safe_deletion", "Historical stepwise"),
        ("heaviest_safe_first", "Heaviest-safe-first"),
        ("weighted_greedy", "Weighted greedy"),
        ("weighted_greedy_reverse_delete", "Greedy + reverse deletion"),
        ("multistart_random_deletion", "32-start deletion"),
        ("preprocessed_highs_mip", "Preprocessed MIP workflow"),
    )
    io = IOBuffer()
    print(io, source_comment("experiments/results/summaries/financial_resource_optimization_weight_robustness_summary.csv"))
    println(io, "\\begin{center}")
    println(io, "\\begin{minipage}{\\textwidth}")
    println(io, "\\centering\\small")
    println(io, "\\resizebox{\\textwidth}{!}{%")
    println(io, "\\begin{tabular}{@{}lrrrr@{}}")
    println(io, "\\toprule")
    println(io, "Algorithm & Terminal validation & Terminal governance & Annual validation & Annual governance \\\\")
    println(io, "\\midrule")
    for (algorithm_id, label) in algorithms
        cells = String[]
        for audit_id in ("locked_terminal_v1", "annual_walk_forward_v2"), schedule_id in ("validation_computation", "governance_complexity")
            row = only_row(rows; audit_id, schedule_id, algorithm_id)
            value = "\\($(tex_exact(row["selected_exact_burden"]))\\)"
            row["attains_exact_preprocessing_optimum"] == "true" && (value = "\\textbf{$value}")
            push!(cells, value)
        end
        println(io, "$label & $(join(cells, " & ")) \\\\")
    end
    println(io, "\\bottomrule")
    println(io, "\\end{tabular}")
    println(io, "}")
    println(io, "\\captionof{table}{Exact rechecked burden by algorithm and prespecified resource schedule. Bold burdens equal the empty-residual exact optimum. Columns use schedule-specific units and terminal and annual cases are not pooled. Equal-active-strategy burdens are omitted because all six algorithms tie at the certified optimum; the machine-readable input retains those rows.}")
    println(io, "\\label{tab:aor-financial-algorithm-burdens}")
    println(io, "\\end{minipage}")
    println(io, "\\end{center}")
    return String(take!(io))
end

function financial_robustness_source(inputs)
    rows = inputs.robustness
    io = IOBuffer()
    print(io, source_comment("experiments/results/summaries/financial_resource_optimization_weight_robustness_summary.csv"))
    println(io, "\\begin{center}")
    println(io, "\\begin{minipage}{\\textwidth}")
    println(io, "\\centering\\scriptsize")
    println(io, "\\setlength{\\tabcolsep}{4pt}")
    println(io, "\\resizebox{\\textwidth}{!}{%")
    println(io, "\\begin{tabular}{@{}llrrrrr@{}}")
    println(io, "\\toprule")
    println(io, "Audit & Schedule & Source burden & Exact optimum & Stepwise burden & Stepwise gap & Active ratio \\\\")
    println(io, "\\midrule")
    for (audit_id, audit_label) in (("locked_terminal_v1", "Terminal"), ("annual_walk_forward_v2", "Annual"))
        for (schedule_id, schedule_label) in (
            ("equal_active_strategy", "Equal"),
            ("validation_computation", "Validation"),
            ("governance_complexity", "Governance"),
        )
            row = only_row(rows; audit_id, schedule_id, algorithm_id = "current_stepwise_safe_deletion")
            gap = "\\($(tex_exact(row["global_stepwise_absolute_gap"]))\\); \\($(tex_exact(row["global_stepwise_relative_gap"]))\\) rel."
            println(io,
                "$audit_label & $schedule_label & \\($(tex_exact(row["source_exact_burden"]))\\) & " *
                "\\($(tex_exact(row["exact_preprocessing_optimum_burden"]))\\) & \\($(tex_exact(row["selected_exact_burden"]))\\) & " *
                "$gap & \\($(tex_exact(row["compression_ratio"]))\\) \\\\",
            )
        end
    end
    println(io, "\\bottomrule")
    println(io, "\\end{tabular}")
    println(io, "}")
    println(io, "\\captionof{table}{Locked burden robustness and global-versus-historical-stepwise gap. The gap columns show absolute and relative excess burden of the historical stepwise endpoint over the exact empty-residual optimum. Active ratio is selected active strategies divided by source active strategies for that endpoint. Exact rational arithmetic is preserved.}")
    println(io, "\\label{tab:aor-financial-robustness}")
    println(io, "\\end{minipage}")
    println(io, "\\end{center}")
    return String(take!(io))
end

function point_in_time_and_mechanism_inputs()
    predecision_path = joinpath(
        POINT_IN_TIME_ROOT,
        "predecision_computation",
        "PREDECISION_COMPUTATION_MANIFEST.toml",
    )
    predecision_seal_path = joinpath(
        POINT_IN_TIME_ROOT,
        "PREDECISION_COMPUTATION_RESULT_SEAL.toml",
    )
    proposal_path = joinpath(
        POINT_IN_TIME_ROOT,
        "proposal_policy",
        "PROPOSAL_POLICY_MANIFEST.toml",
    )
    proposal_seal_path = joinpath(POINT_IN_TIME_ROOT, "PROPOSAL_POLICY_RESULT_SEAL.toml")
    evaluation_path = joinpath(
        POINT_IN_TIME_ROOT,
        "evaluation_results",
        "EVALUATION_RESULT_MANIFEST.toml",
    )
    evaluation_seal_path = joinpath(POINT_IN_TIME_ROOT, "EVALUATION_RESULT_SEAL.toml")
    mechanism_result_path = joinpath(CLOSURE_OPTION_ROOT, "results", "RESULT_MANIFEST.toml")
    mechanism_seal_path = joinpath(CLOSURE_OPTION_ROOT, "RESULT_SEAL.toml")
    mechanism_calibration_path = joinpath(CLOSURE_OPTION_ROOT, "calibration", "CALIBRATION.toml")
    mechanism_config_path = joinpath(
        REPOSITORY_ROOT,
        "experiments",
        "configs",
        "financial_strategy_library_panel_v4.toml",
    )

    predecision = TOML.parsefile(predecision_path)
    predecision_seal = TOML.parsefile(predecision_seal_path)
    proposal = TOML.parsefile(proposal_path)
    proposal_seal = TOML.parsefile(proposal_seal_path)
    evaluation = TOML.parsefile(evaluation_path)
    evaluation_seal = TOML.parsefile(evaluation_seal_path)
    mechanism = TOML.parsefile(mechanism_result_path)
    mechanism_seal = TOML.parsefile(mechanism_seal_path)
    mechanism_calibration = TOML.parsefile(mechanism_calibration_path)
    mechanism_config = TOML.parsefile(mechanism_config_path)

    predecision_seal["status"] == "SEALED_PREDECISION_COMPUTATION_RESULT" ||
        error("point-in-time predecision result is not sealed")
    predecision_seal["public_result_manifest_sha256"] == sha256_file(predecision_path) ||
        error("point-in-time predecision result seal mismatch")
    predecision["return_values_included"] === false ||
        error("point-in-time predecision public manifest contains return values")
    predecision["licensed_security_identifiers_included"] === false ||
        error("point-in-time predecision public manifest contains licensed identifiers")
    predecision["all_exact_postchecks_passed"] === true ||
        error("point-in-time exact postchecks did not pass")

    proposal_seal["status"] == "SEALED_PROPOSAL_POLICY_RESULT" ||
        error("point-in-time proposal policy is not sealed")
    proposal_seal["public_proposal_policy_manifest_sha256"] == sha256_file(proposal_path) ||
        error("point-in-time proposal-policy seal mismatch")
    proposal["evaluation_values_used"] == 0 ||
        error("evaluation values entered point-in-time policy selection")
    proposal["return_values_included"] === false ||
        error("point-in-time proposal public manifest contains return values")
    proposal["selected_strategy_identities_included"] === false ||
        error("point-in-time proposal public manifest contains selected identities")

    evaluation_seal["status"] == "SEALED_HISTORICAL_EVALUATION_RESULT" ||
        error("point-in-time evaluation result is not sealed")
    evaluation_seal["evaluation_result_manifest_sha256"] == sha256_file(evaluation_path) ||
        error("point-in-time evaluation seal mismatch")
    evaluation_seal["result_replay_audit_passed"] === true ||
        error("point-in-time evaluation replay audit did not pass")
    evaluation["return_values_included"] === false ||
        error("point-in-time evaluation public manifest contains raw returns")
    evaluation["licensed_identifiers_included"] === false ||
        error("point-in-time evaluation public manifest contains licensed identifiers")

    mechanism_seal["status"] == "INDEPENDENT_RECOMPUTATION_PASS" ||
        error("closure-option experiment was not independently recomputed")
    mechanism_seal["result_manifest_sha256"] == sha256_file(mechanism_result_path) ||
        error("closure-option result seal mismatch")
    mechanism["status"] == "COMPLETE_REGISTERED_GATES_PASS" ||
        error("closure-option registered gates did not pass")
    mechanism["market_alpha_claim_permitted"] === false ||
        error("closure-option result incorrectly permits a market-alpha claim")
    mechanism["total_world_rows"] == length(mechanism["summaries"]) * mechanism["evaluation_world_count_per_regime"] ||
        error("closure-option world count mismatch")
    mechanism_calibration["return_values_included"] === false ||
        error("closure-option calibration public artifact contains returns")
    mechanism_calibration["security_identifiers_included"] === false ||
        error("closure-option calibration public artifact contains identifiers")

    return (;
        predecision,
        proposal,
        evaluation,
        mechanism,
        mechanism_calibration,
        mechanism_config,
        source_paths = (
            predecision_path,
            predecision_seal_path,
            proposal_path,
            proposal_seal_path,
            evaluation_path,
            evaluation_seal_path,
            mechanism_result_path,
            mechanism_seal_path,
            mechanism_calibration_path,
            mechanism_config_path,
        ),
    )
end

function point_in_time_summary(inputs, universe_id)
    cells = filter(
        cell -> cell["universe_id"] == universe_id && cell["universe_gate_passed"] === true,
        inputs.predecision["cells"],
    )
    isempty(cells) && error("no gate-passed point-in-time cells for $universe_id")
    source_burdens = exact.(getindex.(cells, "source_exact_burden"))
    safe_burdens = exact.(getindex.(cells, "safe_exact_burden"))
    reductions = [1 - safe / source for (safe, source) in zip(safe_burdens, source_burdens)]
    options = parse.(Int, string.(getindex.(cells, "innovation_option_count")))
    summary_key = universe_id == "liquid_common_equity" ? "common_equity_summary" :
        universe_id == "liquid_plain_etf" ? "etf_replication_summary" :
        error("unsupported universe: $universe_id")
    heldout = inputs.evaluation[summary_key]
    return (;
        cells,
        n = length(cells),
        source_mean = sum(source_burdens) / length(source_burdens),
        safe_mean = sum(safe_burdens) / length(safe_burdens),
        reduction_mean = sum(reductions) / length(reductions),
        option_mean = sum(options) / length(options),
        capabilities = unique(getindex.(cells, "complete_capability_count")),
        exact_preprocessing = count(cell -> cell["safe_solved_by_exact_preprocessing"] === true, cells),
        solver_optimal = count(cell -> cell["safe_solver_claimed_optimal"] === true, cells),
        heldout,
    )
end

percent(value; digits = 1) = @sprintf("%.*f", digits, 100 * Float64(value))
decimal(value; digits = 4) = @sprintf("%.*f", digits, Float64(value))

function point_in_time_source(inputs)
    equity = point_in_time_summary(inputs, "liquid_common_equity")
    etf = point_in_time_summary(inputs, "liquid_plain_etf")
    length(equity.capabilities) == 1 && only(equity.capabilities) == 31 ||
        error("unexpected common-equity capability count")
    length(etf.capabilities) == 1 && only(etf.capabilities) == 31 ||
        error("unexpected ETF capability count")
    io = IOBuffer()
    print(io, source_comment(
        "experiments/financial_strategy_library_panel_v3/predecision_computation/PREDECISION_COMPUTATION_MANIFEST.toml",
        "experiments/financial_strategy_library_panel_v3/evaluation_results/EVALUATION_RESULT_MANIFEST.toml",
        "experiments/financial_strategy_library_panel_v3/PREDECISION_COMPUTATION_RESULT_SEAL.toml",
        "experiments/financial_strategy_library_panel_v3/EVALUATION_RESULT_SEAL.toml",
    ))
    println(io, "\\begin{table}[tbp]")
    println(io, "\\centering\\small")
    println(io, "\\setlength{\\tabcolsep}{3.6pt}")
    println(io, "\\resizebox{\\textwidth}{!}{%")
    println(io, "\\begin{tabular}{@{}lrrrrrr@{}}")
    println(io, "\\toprule")
    println(io, "Universe & Origins & Mean source burden & Mean safe burden & Mean reduction & Added options & Held-out CE difference \\\\")
    println(io, "\\midrule")
    println(io, "Common equity & $(equity.n) & $(decimal(equity.source_mean; digits = 1)) & $(decimal(equity.safe_mean; digits = 1)) & $(percent(equity.reduction_mean))\\% & $(decimal(equity.option_mean; digits = 2)) & $(decimal(equity.heldout["arithmetic_mean"]; digits = 4)) \\\\")
    println(io, "Plain ETF & $(etf.n) & $(decimal(etf.source_mean; digits = 1)) & $(decimal(etf.safe_mean; digits = 1)) & $(percent(etf.reduction_mean))\\% & $(decimal(etf.option_mean; digits = 2)) & $(decimal(etf.heldout["arithmetic_mean"]; digits = 4)) \\\\")
    println(io, "\\bottomrule")
    println(io, "\\end{tabular}")
    println(io, "}")
    println(io, "\\caption{Point-in-time portfolio-library retention results. Burden is the registered validation-computation index, not currency. Added options are safe-library proposal actions absent from the budget-matched frontier-only library. The held-out column is innovation-safe minus frontier-only certainty-equivalent difference: all $(equity.heldout["complete_origin_count"]) common-equity choices coincide, while one of $(etf.heldout["complete_origin_count"]) complete ETF choices differs. Safe solutions pass exact original-instance frontier, closure, inactive-retention, and burden rechecks; solver-reported optimality remains solver evidence.}")
    println(io, "\\label{tab:point-in-time-financial-study}")
    println(io, "\\end{table}")
    return String(take!(io))
end

function closure_option_source(inputs)
    labels = Dict(
        "adversarial_margin" => "Adverse margin",
        "null_margin" => "Null margin",
        "low_dose_positive" => "Low positive dose",
        "powered_positive" => "Powered positive dose",
    )
    order = Dict(
        "adversarial_margin" => 1,
        "null_margin" => 2,
        "low_dose_positive" => 3,
        "powered_positive" => 4,
    )
    rows = sort(inputs.mechanism["summaries"]; by = row -> order[row["regime_id"]])
    io = IOBuffer()
    print(io, source_comment(
        "experiments/financial_strategy_library_panel_v4/results/RESULT_MANIFEST.toml",
        "experiments/financial_strategy_library_panel_v4/RESULT_SEAL.toml",
    ))
    println(io, "\\begin{table}[tbp]")
    println(io, "\\centering\\small")
    println(io, "\\setlength{\\tabcolsep}{3.5pt}")
    println(io, "\\resizebox{\\textwidth}{!}{%")
    println(io, "\\begin{tabular}{@{}lrrrr@{}}")
    println(io, "\\toprule")
    println(io, "Regime & True margin & Oracle mean [95\\% CI] & Learned mean [95\\% CI] & Adoption \\\\")
    println(io, "\\midrule")
    for row in rows
        println(io,
            "$(labels[row["regime_id"]]) & $(decimal(row["true_margin"]; digits = 4)) & " *
            "$(decimal(row["oracle_mean"]; digits = 4)) [$(decimal(row["oracle_ci_lower"]; digits = 4)), $(decimal(row["oracle_ci_upper"]; digits = 4))] & " *
            "$(decimal(row["learned_mean"]; digits = 4)) [$(decimal(row["learned_ci_lower"]; digits = 4)), $(decimal(row["learned_ci_upper"]; digits = 4))] & " *
            "$(percent(row["adoption_rate"]; digits = 2))\\% \\\\",
        )
    end
    println(io, "\\bottomrule")
    println(io, "\\end{tabular}")
    println(io, "}")
    println(io, "\\caption{Calibrated closure-option mechanism experiment, with $(inputs.mechanism["evaluation_world_count_per_regime"]) synthetic worlds per prespecified regime. Current frontier and burden are equal by construction; only the innovation-safe library can admit the designated bridge descendant. Intervals are registered finite-simulation uncertainty summaries. This is synthetic mechanism evidence, not a market-return, alpha, forecasting, or causal estimate.}")
    println(io, "\\label{tab:closure-option-mechanism}")
    println(io, "\\end{table}")
    return String(take!(io))
end

function point_in_time_origin_source(inputs)
    equity = Dict(row["origin_id"] => row for row in inputs.evaluation["common_equity_summary"]["origin_values"])
    etf = Dict(row["origin_id"] => row for row in inputs.evaluation["etf_replication_summary"]["origin_values"])
    origins = sort(collect(union(keys(equity), keys(etf))))
    io = IOBuffer()
    print(io, source_comment(
        "experiments/financial_strategy_library_panel_v3/evaluation_results/EVALUATION_RESULT_MANIFEST.toml",
    ))
    println(io, "\\begin{longtable}{@{}lrrrr@{}}")
    println(io, "\\caption{Origin-level point-in-time held-out contrasts. CE differences are innovation-safe minus frontier-only. A dash marks the prespecified failed ETF universe gate; it is retained, not imputed.}\\label{tab:point-in-time-origin-results}\\\\")
    println(io, "\\toprule")
    println(io, "Origin & Equity CE diff. & Same choice & ETF CE diff. & Same choice \\\\")
    println(io, "\\midrule")
    println(io, "\\endfirsthead")
    println(io, "\\toprule")
    println(io, "Origin & Equity CE diff. & Same choice & ETF CE diff. & Same choice \\\\")
    println(io, "\\midrule")
    println(io, "\\endhead")
    for origin in origins
        erow = equity[origin]
        trow = etf[origin]
        evalue = erow["complete"] === true ? decimal(erow["certainty_equivalent_difference"]; digits = 4) : "--"
        tvalue = trow["complete"] === true ? decimal(trow["certainty_equivalent_difference"]; digits = 4) : "--"
        esame = erow["complete"] === true ? (erow["same_choice"] === true ? "yes" : "no") : "--"
        tsame = trow["complete"] === true ? (trow["same_choice"] === true ? "yes" : "no") : "--"
        println(io, "$(replace(origin, "FSLP3-O" => "")) & $evalue & $esame & $tvalue & $tsame \\\\")
    end
    println(io, "\\bottomrule")
    println(io, "\\end{longtable}")
    return String(take!(io))
end

function point_in_time_and_mechanism_macros(inputs)
    equity = point_in_time_summary(inputs, "liquid_common_equity")
    etf = point_in_time_summary(inputs, "liquid_plain_etf")
    null = only(filter(row -> row["regime_id"] == "null_margin", inputs.mechanism["summaries"]))
    low = only(filter(row -> row["regime_id"] == "low_dose_positive", inputs.mechanism["summaries"]))
    powered = only(filter(row -> row["regime_id"] == "powered_positive", inputs.mechanism["summaries"]))
    return source_comment(
        "experiments/financial_strategy_library_panel_v3/predecision_computation/PREDECISION_COMPUTATION_MANIFEST.toml",
        "experiments/financial_strategy_library_panel_v3/evaluation_results/EVALUATION_RESULT_MANIFEST.toml",
        "experiments/financial_strategy_library_panel_v4/results/RESULT_MANIFEST.toml",
        "experiments/configs/financial_strategy_library_panel_v4.toml",
    ) * """
\\newcommand{\\AORPointInTimeEquityOrigins}{$(equity.n)}
\\newcommand{\\AORPointInTimeETFOrigins}{$(etf.n)}
\\newcommand{\\AORPointInTimeCapabilities}{$(only(equity.capabilities))}
\\newcommand{\\AORPointInTimeEquityBurdenReduction}{$(percent(equity.reduction_mean))\\%}
\\newcommand{\\AORPointInTimeETFBurdenReduction}{$(percent(etf.reduction_mean))\\%}
\\newcommand{\\AORPointInTimeEquityAddedOptions}{$(decimal(equity.option_mean; digits = 2))}
\\newcommand{\\AORPointInTimeETFAddedOptions}{$(decimal(etf.option_mean; digits = 2))}
\\newcommand{\\AORPointInTimeEquityPolicyReplacements}{$(equity.heldout["complete_origin_count"] - equity.heldout["same_choice_count"])}
\\newcommand{\\AORPointInTimeETFPolicyReplacements}{$(etf.heldout["complete_origin_count"] - etf.heldout["same_choice_count"])}
\\newcommand{\\AORPointInTimeETFMeanCE}{$(decimal(etf.heldout["arithmetic_mean"]; digits = 4))}
\\newcommand{\\AORPointInTimeETFMinimumCE}{$(decimal(etf.heldout["minimum"]; digits = 4))}
\\newcommand{\\AORPointInTimePreprocessingSolutions}{$(equity.exact_preprocessing + etf.exact_preprocessing)}
\\newcommand{\\AORPointInTimeSolverSolutions}{$(equity.solver_optimal + etf.solver_optimal)}
\\newcommand{\\AORPointInTimeCompletePaths}{$(inputs.mechanism_calibration["complete_strategy_path_count"])}
\\newcommand{\\AORPointInTimeResidualObservations}{$(inputs.mechanism_calibration["available_residual_observation_count"])}
\\newcommand{\\AORClosureOptionWorlds}{$(inputs.mechanism["evaluation_world_count_per_regime"])}
\\newcommand{\\AORClosureNullAdoption}{$(percent(null["adoption_rate"]; digits = 2))\\%}
\\newcommand{\\AORClosureNullWilsonUpper}{$(percent(null["adoption_wilson_upper"]; digits = 2))\\%}
\\newcommand{\\AORClosureNullAdoptionGate}{$(percent(inputs.mechanism_config["success_gates"]["null_false_adoption_rate_maximum"]; digits = 1))\\%}
\\newcommand{\\AORClosureLowDoseAdoption}{$(percent(low["adoption_rate"]; digits = 2))\\%}
\\newcommand{\\AORClosurePoweredAdoption}{$(percent(powered["adoption_rate"]; digits = 2))\\%}
\\newcommand{\\AORClosurePoweredMargin}{$(decimal(powered["true_margin"]; digits = 4))}
\\newcommand{\\AORClosurePoweredLearnedMean}{$(decimal(powered["learned_mean"]; digits = 4))}
"""
end

function sources()
    algorithm_inputs = audit_inputs()
    financial = financial_inputs()
    journal_financial = point_in_time_and_mechanism_inputs()
    common_macros = macros_source(algorithm_inputs) * point_in_time_and_mechanism_macros(journal_financial)
    point_in_time = point_in_time_source(journal_financial)
    closure_option = closure_option_source(journal_financial)
    return Dict(
        "macros" => common_macros,
        "resource_macros" => common_macros,
        "scaling" => scaling_source(),
        "heuristics" => heuristic_source(),
        "preprocessing" => preprocessing_source(),
        "adversarial" => adversarial_source(),
        "financial_instances" => financial_instance_source(financial),
        "financial_algorithms" => financial_algorithm_source(financial),
        "financial_robustness" => financial_robustness_source(financial),
        "point_in_time_study" => point_in_time,
        "closure_option_experiment" => closure_option,
        "resource_point_in_time_study" => point_in_time,
        "resource_closure_option_experiment" => closure_option,
        "resource_point_in_time_origins" => point_in_time_origin_source(journal_financial),
    )
end

function generate(; check::Bool = false)
    generated = sources()
    for key in sort(collect(keys(OUTPUTS)))
        path = OUTPUTS[key]
        content = generated[key]
        if check
            isfile(path) || error("missing generated input: $path")
            read(path, String) == content || error("generated input drift: $path")
        else
            mkpath(dirname(path))
            open(path, "w") do io
                write(io, content)
            end
        end
    end
    return true
end

function main(args = ARGS)
    if isempty(args) || args == ["--write"]
        generate()
        println("aor-manuscript-evidence: generated $(length(OUTPUTS)) inputs")
    elseif args == ["--check"]
        generate(; check = true)
        println("aor-manuscript-evidence: PASS")
    else
        error("usage: build_aor_manuscript_evidence_inputs.jl [--write|--check]")
    end
end

if abspath(PROGRAM_FILE) == @__FILE__
    main()
end

end
