module JournalEvidenceFixtureExporter

using TOML

export check_outputs, fixture_payload, main, write_outputs

const REPOSITORY_ROOT = normpath(joinpath(@__DIR__, "..", ".."))
const FIXTURE_PATH = joinpath(
    REPOSITORY_ROOT,
    "journal",
    "aor",
    "fixtures",
    "journal_formal_evidence_v1.toml",
)
const LEAN_PATH = joinpath(
    REPOSITORY_ROOT,
    "formal",
    "StrategyInnovation",
    "Fixtures",
    "JournalAlgorithms.lean",
)

const GAP_K = 4
const GAP_EPSILON = big(1) // big(2)
const GAP_HEURISTIC_BURDEN = GAP_K // 1
const GAP_OPTIMUM_BURDEN = 1 // 1 + GAP_EPSILON
const GAP_RATIO = GAP_HEURISTIC_BURDEN / GAP_OPTIMUM_BURDEN

const DP_LEFT_MASK = Bool[true, false, true]
const DP_RIGHT_MASK = Bool[false, true, false]
const DP_TAKE_MASK = DP_LEFT_MASK .| DP_RIGHT_MASK

const GREEDY_FIXTURE_BURDEN = 1 // 1 + 1 // 2 + 1 // 3
const GREEDY_FIXTURE_OPTIMUM = 1 // 1 + 1 // 12
const GREEDY_FIXTURE_RATIO = GREEDY_FIXTURE_BURDEN / GREEDY_FIXTURE_OPTIMUM

_exact(value::Rational) = "$(numerator(value))//$(denominator(value))"


function fixture_payload()
    return Dict{String,Any}(
        "schema_version" => "journal-formal-evidence-fixture-v1",
        "fixture_id" => "AOR-JOURNAL-EVIDENCE-01",
        "evidence_boundary" =>
            "exact finite Julia-Lean agreement only; no universal complexity, preprocessing-optimality, dynamic-programming, approximation, or implementation proof",
        "gap" => Dict(
            "k" => GAP_K,
            "epsilon" => _exact(GAP_EPSILON),
            "heuristic_burden" => _exact(GAP_HEURISTIC_BURDEN),
            "optimum_burden" => _exact(GAP_OPTIMUM_BURDEN),
            "ratio" => _exact(GAP_RATIO),
        ),
        "requirement_mask" => Dict(
            "left" => DP_LEFT_MASK,
            "right" => DP_RIGHT_MASK,
            "take_union" => DP_TAKE_MASK,
        ),
        "preprocessing" => Dict(
            "requirement_count" => 3,
            "strategy_coverage" => [
                Bool[true, false, false],
                Bool[false, true, true],
                Bool[false, false, true],
            ],
            "unique_requirement_index" => 0,
            "forced_strategy_index" => 0,
        ),
        "weighted_greedy" => Dict(
            "singleton_burden" => _exact(GREEDY_FIXTURE_BURDEN),
            "bundle_burden" => _exact(GREEDY_FIXTURE_OPTIMUM),
            "ratio" => _exact(GREEDY_FIXTURE_RATIO),
        ),
    )
end


function _toml_text()
    io = IOBuffer()
    TOML.print(io, fixture_payload(); sorted = true)
    return String(take!(io))
end


function _lean_text()
    return """import StrategyInnovation.Optimization.TaggedCoverPreprocessing
import Mathlib.Tactic.FinCases
import Mathlib.Tactic.NormNum

/-!
# Generated exact journal evidence fixtures

Generated by `julia/scripts/export_journal_evidence_fixtures.jl` from the
same exact Julia values as `journal_formal_evidence_v1.toml`. These theorems
check only the displayed finite arithmetic and coverage instances. They do
not formalize a universal complexity, preprocessing-optimality,
dynamic-programming, approximation, or implementation theorem.
-/

namespace StrategyInnovation

namespace Fixtures

namespace JournalAlgorithms

def gapK : ℕ := $GAP_K
def gapEpsilon : ℚ := $(numerator(GAP_EPSILON)) / $(denominator(GAP_EPSILON))
def gapHeuristicBurden : ℚ := $GAP_K
def gapOptimumBurden : ℚ := 1 + gapEpsilon

/-- The shared `k=4`, `epsilon=1/2` deletion-gap fixture has ratio `8/3`. -/
theorem gap_k4_half_ratio_exact :
    gapHeuristicBurden / gapOptimumBurden = (8 : ℚ) / 3 := by
  norm_num [gapHeuristicBurden, gapOptimumBurden, gapEpsilon]

def maskOr : List Bool → List Bool → List Bool
  | left :: lefts, right :: rights => (left || right) :: maskOr lefts rights
  | _, _ => []

/-- The shared DP take transition forms full coverage by exact mask union. -/
theorem requirementMask_take_union_exact :
    maskOr [true, false, true] [false, true, false] = [true, true, true] := by
  decide

def preprocessingCoverage : Fin 3 → Finset (Fin 3)
  | 0 => {0}
  | 1 => {1, 2}
  | 2 => {2}

def preprocessingRequirements : Finset (Fin 3) := Finset.univ

/-- Requirement zero has strategy zero as its unique carrier in the shared fixture. -/
theorem preprocessing_unique_first_carrier
    (strategy : Fin 3)
    (hcarrier : (0 : Fin 3) ∈ preprocessingCoverage strategy) :
    strategy = 0 := by
  fin_cases strategy <;> simp [preprocessingCoverage] at hcarrier ⊢

/-- Every cover of the shared fixture selects its unique first carrier. -/
theorem preprocessing_fixture_forces_first
    (selected : Finset (Fin 3))
    (hcover :
      Optimization.TaggedCoverPreprocessing.SelectedCovers
        preprocessingCoverage preprocessingRequirements selected) :
    (0 : Fin 3) ∈ selected := by
  exact Optimization.TaggedCoverPreprocessing.uniqueCarrier_mem_of_selectedCovers
    preprocessingCoverage preprocessingRequirements selected
    (by simp [preprocessingRequirements]) preprocessing_unique_first_carrier hcover

def greedySingletonBurden : ℚ := 1 + 1 / 2 + 1 / 3
def greedyBundleBurden : ℚ := 1 + 1 / 12

/-- Exact arithmetic for the shared three-row Chvatal near-tight fixture. -/
theorem greedy_three_row_ratio_exact :
    greedySingletonBurden / greedyBundleBurden = (22 : ℚ) / 13 := by
  norm_num [greedySingletonBurden, greedyBundleBurden]

end JournalAlgorithms

end Fixtures

end StrategyInnovation
"""
end


function _write_replace(path::AbstractString, text::AbstractString)
    mkpath(dirname(path))
    temporary = path * ".tmp.$(getpid())"
    open(temporary, "w") do io
        write(io, text)
    end
    mv(temporary, path; force = true)
    return path
end


function write_outputs()
    _write_replace(FIXTURE_PATH, _toml_text())
    _write_replace(LEAN_PATH, _lean_text())
    println("wrote exact Julia-Lean journal evidence fixtures")
    return (FIXTURE_PATH, LEAN_PATH)
end


function check_outputs()
    isfile(FIXTURE_PATH) || error("journal evidence TOML fixture is absent")
    isfile(LEAN_PATH) || error("journal evidence Lean fixture is absent")
    read(FIXTURE_PATH, String) == _toml_text() || error(
        "journal evidence TOML fixture drift",
    )
    read(LEAN_PATH, String) == _lean_text() || error(
        "journal evidence Lean fixture drift",
    )
    println("exact Julia-Lean journal evidence fixtures match")
    return true
end


function main(args = ARGS)
    length(args) == 1 || error(
        "usage: export_journal_evidence_fixtures.jl --write|--check",
    )
    only(args) == "--write" && return write_outputs()
    only(args) == "--check" && return check_outputs()
    error("unknown mode: $(only(args))")
end

end

if abspath(PROGRAM_FILE) == @__FILE__
    JournalEvidenceFixtureExporter.main()
end
