module FigureAuditArtifacts

using Printf

export check_figure_audit_artifacts, generate_figure_audit_artifacts, main

const REPOSITORY_ROOT = normpath(joinpath(@__DIR__, "..", ".."))
const SUMMARY_ROOT = joinpath(REPOSITORY_ROOT, "experiments", "results", "summaries")
const BRIDGE_DATA = joinpath(SUMMARY_ROOT, "innovation_safe_bridge.csv")
const CAPACITY_DATA =
    joinpath(SUMMARY_ROOT, "unified_elasticity_switching_v1_capacity.csv")
const PENALTY_DATA =
    joinpath(SUMMARY_ROOT, "unified_elasticity_switching_v1_penalized_path.csv")
const OUTPUTS = Dict(
    "bridge" => joinpath(
        REPOSITORY_ROOT,
        "manuscript",
        "figures",
        "innovation_safe_bridge.tex",
    ),
    "economic_geometry" => joinpath(
        REPOSITORY_ROOT,
        "manuscript",
        "figures",
        "unified_economic_geometry.tex",
    ),
)

function _parse_csv(path::AbstractString)
    lines = readlines(path)
    isempty(lines) && error("empty CSV: $path")
    header = split(first(lines), ',')
    length(unique(header)) == length(header) || error("duplicate CSV header: $path")
    rows = Dict{String,String}[]
    for line in Iterators.drop(lines, 1)
        isempty(strip(line)) && continue
        fields = split(line, ','; keepempty = true)
        length(fields) == length(header) || error("malformed CSV row in $path")
        push!(rows, Dict(header .=> fields))
    end
    return rows
end

function _exact(value::AbstractString)
    isempty(value) && error("empty exact rational")
    parts = split(value, "//")
    length(parts) == 1 && return parse(BigInt, only(parts)) // BigInt(1)
    length(parts) == 2 || error("invalid exact rational: $value")
    return parse(BigInt, parts[1]) // parse(BigInt, parts[2])
end

function _tex_exact(value::AbstractString)
    rational = _exact(value)
    denominator(rational) == 1 && return string(numerator(rational))
    return "\\\\frac{$(numerator(rational))}{$(denominator(rational))}"
end

_decimal(value; digits::Integer = 5) = string(round(Float64(value); digits))
_map(value, minimum, maximum, origin, span) =
    origin + span * (Float64(value) - Float64(minimum)) /
        (Float64(maximum) - Float64(minimum))

function _only_row(rows, key::AbstractString, value::AbstractString)
    selected = filter(row -> row[key] == value, rows)
    length(selected) == 1 || error("expected one row with $key=$value")
    return only(selected)
end

function _validate_bridge_rows(rows)
    length(rows) == 5 || error("bridge data must contain five entities")
    expected = Dict(
        "s_L" => ("strategy", "3//1", "1//1", "", ""),
        "s_R" => ("strategy", "1//1", "3//1", "", ""),
        "s_M" => ("strategy", "1//1", "1//1", "m", ""),
        "q" => ("project", "", "", "", "m"),
        "c" => ("descendant", "4//1", "4//1", "", ""),
    )
    for (entity, values) in expected
        row = _only_row(rows, "entity_id", entity)
        observed = (
            row["entity_type"],
            row["profile_b_minus"],
            row["profile_b_plus"],
            row["module_id"],
            row["requires_module"],
        )
        observed == values || error("bridge entity drift: $entity")
    end
    return rows
end

function _bridge_source(rows)
    _validate_bridge_rows(rows)
    left = _only_row(rows, "entity_id", "s_L")
    right = _only_row(rows, "entity_id", "s_R")
    bridge = _only_row(rows, "entity_id", "s_M")
    descendant = _only_row(rows, "entity_id", "c")
    return """% Generated by julia/scripts/generate_figure_audit_artifacts.jl.
% Exact source: experiments/results/summaries/innovation_safe_bridge.csv.
\\begin{tikzpicture}[x=1cm,y=0.76cm,font=\\footnotesize]
  \\tikzset{
    active/.style={draw=blue!70!black,fill=blue!8,rounded corners=2pt,
      minimum width=3.30cm,minimum height=0.80cm,align=center},
    bridge/.style={draw=orange!85!black,fill=orange!12,rounded corners=2pt,
      minimum width=3.30cm,minimum height=0.80cm,align=center},
    module/.style={draw=orange!85!black,fill=orange!15,circle,
      minimum size=1.20cm,align=center},
    project/.style={draw=black!55,fill=black!3,rounded corners=2pt,
      minimum width=2.30cm,minimum height=0.86cm,align=center},
    descendant/.style={draw=black!65,fill=black!3,rounded corners=2pt,
      minimum width=2.50cm,minimum height=0.86cm,align=center},
    flow/.style={->,line width=0.95pt,draw=black!70}
  }
  \\draw[draw=black!25,rounded corners=3pt,fill=black!1]
    (-0.2,-0.78) rectangle (3.90,4.75);
  \\node[font=\\bfseries,anchor=west] at (0.05,4.40)
    {exact retained library \\(L\\)};

  \\node[active] (left) at (1.85,3.42)
    {\\(s_L:($(_tex_exact(left["profile_b_minus"])),$(_tex_exact(left["profile_b_plus"])))\\)\\\\frontier-active at \\(b^-\\)};
  \\node[active] (right) at (1.85,2.18)
    {\\(s_R:($(_tex_exact(right["profile_b_minus"])),$(_tex_exact(right["profile_b_plus"])))\\)\\\\frontier-active at \\(b^+\\)};
  \\node[bridge] (bridge) at (1.85,0.38)
    {\\(s_M:($(_tex_exact(bridge["profile_b_minus"])),$(_tex_exact(bridge["profile_b_plus"])))\\)\\\\dominated unique carrier};

  \\node[draw=blue!70!black,fill=blue!6,rounded corners=2pt,
    minimum width=2.55cm,minimum height=0.80cm,align=center]
    (frontier) at (5.48,2.82) {current frontier\\\\\\(F_L=(3,3)\\)};
  \\draw[flow,draw=blue!65!black] (left.east) -- (frontier.west);
  \\draw[flow,draw=blue!65!black] (right.east) -- (frontier.west);

  \\node[module] (module) at (5.48,0.38) {unique\\\\module \\(m\\)};
  \\draw[flow,draw=orange!85!black] (bridge.east) -- (module.west);
  \\node[project] (project) at (8.45,0.38) {project \\(q\\)\\\\requires \\(m\\)};
  \\draw[flow,draw=orange!85!black] (module.east) -- (project.west);
  \\node[descendant] (descendant) at (11.75,0.38)
    {enabled descendant \\(c\\)\\\\profile \\($(_tex_exact(descendant["profile_b_minus"])),$(_tex_exact(descendant["profile_b_plus"]))\\)};
  \\draw[flow] (project.east) -- (descendant.west);

  \\draw[dashed,orange!85!black,line width=0.85pt]
    (4.00,-1.18) rectangle (13.18,1.34);
  \\node[anchor=west,text=orange!78!black,font=\\scriptsize] at (4.15,-0.87)
    {deleting \\(s_M\\) removes the exact module--project--descendant path};
\\end{tikzpicture}
"""
end

const SCHEDULE_STYLE = Dict(
    "equal_active" => ("blue!72!black", "solid"),
    "descendant_heavy" => ("orange!85!black", "densely dashed"),
)

function _validate_geometry_rows(capacity, penalty)
    length(capacity) == 30 || error("capacity source must contain 30 exact rows")
    length(penalty) == 24 || error("penalty source must contain 24 exact rows")
    all(row["all_optima_feasible"] == "true" && row["ties_complete"] == "true" for row in capacity) ||
        error("capacity source failed its exact optimizer gates")
    all(row["ties_complete"] == "true" for row in penalty) ||
        error("penalty source failed its exact optimizer-tie gate")
    for row in capacity
        _exact(row["capacity"])
        _exact(row["optimal_objective"])
    end
    for row in penalty
        _exact(row["lower_price"])
        isempty(row["upper_price"]) || _exact(row["upper_price"])
        _exact(row["selected_burden"])
        _exact(row["productive_value"])
    end
    return nothing
end

function _axes(
    io;
    x,
    y,
    width,
    height,
    xmin,
    xmax,
    ymin,
    ymax,
    xticks,
    yticks,
    facet,
    show_y = false,
)
    println(io, "  \\node[font=\\bfseries\\scriptsize,anchor=south west] at ($x,$(_decimal(y + height + 0.08))) {$facet};")
    println(io, "  \\draw[black!65] ($x,$y) -- ($(_decimal(x + width)),$y);")
    println(io, "  \\draw[black!65] ($x,$y) -- ($x,$(_decimal(y + height)));")
    for tick in xticks
        xx = _map(tick, xmin, xmax, x, width)
        println(io, "  \\draw[black!16] ($(_decimal(xx)),$y) -- ($(_decimal(xx)),$(_decimal(y + height)));")
        println(io, "  \\node[anchor=north,font=\\scriptsize] at ($(_decimal(xx)),$(_decimal(y - 0.05))) {$tick};")
    end
    for tick in yticks
        yy = _map(tick, ymin, ymax, y, height)
        println(io, "  \\draw[black!16] ($x,$(_decimal(yy))) -- ($(_decimal(x + width)),$(_decimal(yy)));")
        show_y && println(io, "  \\node[anchor=east,font=\\scriptsize] at ($(_decimal(x - 0.08)),$(_decimal(yy))) {$tick};")
    end
end

function _capacity_panel(io, rows, belief, x, y, width, height)
    xmin, xmax = 1 // 1, 6 // 1
    ymin, ymax = 0 // 1, 8 // 1
    _axes(
        io;
        x,
        y,
        width,
        height,
        xmin,
        xmax,
        ymin,
        ymax,
        xticks = 1:6,
        yticks = (0, 4, 8),
        facet = belief == "low" ? "low belief" : "high belief",
        show_y = belief == "low",
    )
    for schedule in ("equal_active", "descendant_heavy")
        selected = filter(row -> row["belief"] == belief && row["schedule"] == schedule, rows)
        sort!(selected; by = row -> _exact(row["capacity"]))
        points = Tuple{Rational{BigInt},Rational{BigInt}}[]
        push!(points, (_exact(first(selected)["capacity"]), _exact(first(selected)["optimal_objective"])))
        for index in 2:length(selected)
            capacity = _exact(selected[index]["capacity"])
            push!(points, (capacity, _exact(selected[index - 1]["optimal_objective"])))
            push!(points, (capacity, _exact(selected[index]["optimal_objective"])))
        end
        color, dash = SCHEDULE_STYLE[schedule]
        path = join((
            "($(_decimal(_map(capacity, xmin, xmax, x, width))),$(_decimal(_map(value, ymin, ymax, y, height))))" for
            (capacity, value) in points
        ), " -- ")
        println(io, "  \\draw[$color,$dash,line width=1.05pt] $path;")
        for row in selected
            xx = _map(_exact(row["capacity"]), xmin, xmax, x, width)
            yy = _map(_exact(row["optimal_objective"]), ymin, ymax, y, height)
            println(io, "  \\fill[$color] ($(_decimal(xx)),$(_decimal(yy))) circle (0.035);")
        end
    end
end

function _penalty_segments(rows, belief, schedule)
    selected = filter(
        row -> row["belief"] == belief && row["schedule"] == schedule &&
               row["cell_kind"] != "breakpoint",
        rows,
    )
    sort!(selected; by = row -> _exact(row["lower_price"]))
    return selected
end

function _envelope_panel(io, rows, belief, x, y, width, height)
    xmin, xmax = 0 // 1, 10 // 1
    ymin, ymax = -10 // 1, 8 // 1
    _axes(
        io;
        x,
        y,
        width,
        height,
        xmin,
        xmax,
        ymin,
        ymax,
        xticks = (0, 5, 10),
        yticks = (-10, 0, 8),
        facet = belief == "low" ? "low belief" : "high belief",
        show_y = belief == "low",
    )
    for schedule in ("equal_active", "descendant_heavy")
        color, dash = SCHEDULE_STYLE[schedule]
        for row in _penalty_segments(rows, belief, schedule)
            left = _exact(row["lower_price"])
            right = isempty(row["upper_price"]) ? xmax : min(_exact(row["upper_price"]), xmax)
            value = _exact(row["productive_value"])
            burden = _exact(row["selected_burden"])
            yleft = value - left * burden
            yright = value - right * burden
            println(
                io,
                "  \\draw[$color,$dash,line width=1.05pt] " *
                "($(_decimal(_map(left, xmin, xmax, x, width))),$(_decimal(_map(yleft, ymin, ymax, y, height)))) -- " *
                "($(_decimal(_map(right, xmin, xmax, x, width))),$(_decimal(_map(yright, ymin, ymax, y, height))));",
            )
        end
        breakpoints = filter(
            row -> row["belief"] == belief && row["schedule"] == schedule &&
                   row["cell_kind"] == "breakpoint" && _exact(row["probe_price"]) > 0,
            rows,
        )
        for row in breakpoints
            price = _exact(row["probe_price"])
            net = _exact(row["productive_value"]) - price * _exact(row["selected_burden"])
            println(io, "  \\fill[$color] ($(_decimal(_map(price, xmin, xmax, x, width))),$(_decimal(_map(net, ymin, ymax, y, height)))) circle (0.04);")
        end
    end
end

function _burden_panel(io, rows, belief, x, y, width, height)
    xmin, xmax = 0 // 1, 10 // 1
    ymin, ymax = 4 // 5, 16 // 5
    _axes(
        io;
        x,
        y,
        width,
        height,
        xmin,
        xmax,
        ymin,
        ymax,
        xticks = (0, 5, 10),
        yticks = (1, 2, 3),
        facet = belief == "low" ? "low belief" : "high belief",
        show_y = belief == "low",
    )
    for schedule in ("equal_active", "descendant_heavy")
        color, dash = SCHEDULE_STYLE[schedule]
        segments = _penalty_segments(rows, belief, schedule)
        for row in segments
            left = _exact(row["lower_price"])
            right = isempty(row["upper_price"]) ? xmax : min(_exact(row["upper_price"]), xmax)
            burden = _exact(row["selected_burden"])
            yy = _map(burden, ymin, ymax, y, height)
            println(
                io,
                "  \\draw[$color,$dash,line width=1.15pt] " *
                "($(_decimal(_map(left, xmin, xmax, x, width))),$(_decimal(yy))) -- " *
                "($(_decimal(_map(right, xmin, xmax, x, width))),$(_decimal(yy)));")
        end
        length(segments) == 2 || error("expected two active penalty intervals")
        before, after = segments
        breakpoint = _exact(after["lower_price"])
        xbreak = _map(breakpoint, xmin, xmax, x, width)
        ybefore = _map(_exact(before["selected_burden"]), ymin, ymax, y, height)
        yafter = _map(_exact(after["selected_burden"]), ymin, ymax, y, height)
        println(io, "  \\draw[$color,line width=0.75pt,fill=white] ($(_decimal(xbreak)),$(_decimal(ybefore))) circle (0.045);")
        println(io, "  \\fill[$color] ($(_decimal(xbreak)),$(_decimal(yafter))) circle (0.045);")
    end
end

function _economic_geometry_source(capacity, penalty)
    _validate_geometry_rows(capacity, penalty)
    io = IOBuffer()
    println(io, "% Generated by julia/scripts/generate_figure_audit_artifacts.jl.")
    println(io, "% Exact sources: unified_elasticity_switching_v1_{capacity,penalized_path}.csv.")
    println(io, "\\begin{tikzpicture}[x=1cm,y=1cm,font=\\scriptsize]")
    println(io, "  \\draw[blue!72!black,line width=1.05pt] (3.55,10.95) -- (4.05,10.95);")
    println(io, "  \\node[anchor=west] at (4.15,10.95) {equal-active = carrier-heavy};")
    println(io, "  \\draw[orange!85!black,densely dashed,line width=1.05pt] (10.35,10.95) -- (10.85,10.95);")
    println(io, "  \\node[anchor=west] at (10.95,10.95) {descendant-heavy};")

    println(io, "  \\node[font=\\bfseries\\footnotesize,anchor=west] at (0.25,10.40) {(a) Display-capacity value \\(\\widetilde V^\\star(b;\\widetilde B)\\): exact right-continuous stairs};")
    _capacity_panel(io, capacity, "low", 1.00, 7.75, 6.25, 2.00)
    _capacity_panel(io, capacity, "high", 8.65, 7.75, 6.25, 2.00)
    println(io, "  \\node[anchor=north] at (7.95,7.18) {display capacity \\(\\widetilde B\\)};")
    println(io, "  \\node[rotate=90] at (0.27,8.75) {optimized value};")

    println(io, "  \\node[font=\\bfseries\\footnotesize,anchor=west] at (0.25,6.48) {(b) Display penalized value \\(\\widetilde J^\\star(b;\\lambda)\\): exact active affine branches};")
    _envelope_panel(io, penalty, "low", 1.00, 3.75, 6.25, 2.00)
    _envelope_panel(io, penalty, "high", 8.65, 3.75, 6.25, 2.00)
    println(io, "  \\node[anchor=north] at (7.95,3.18) {resource price \\(\\lambda\\)};")
    println(io, "  \\node[rotate=90] at (0.27,4.75) {display penalized value};")

    println(io, "  \\node[font=\\bfseries\\footnotesize,anchor=west] at (0.25,2.48) {(c) Selected display burden \\(\\widetilde W(L^\\star(\\lambda))\\) under the declared tie rule};")
    _burden_panel(io, penalty, "low", 1.00, -0.25, 6.25, 2.00)
    _burden_panel(io, penalty, "high", 8.65, -0.25, 6.25, 2.00)
    println(io, "  \\node[anchor=north] at (7.95,-0.82) {resource price \\(\\lambda\\)};")
    println(io, "  \\node[rotate=90] at (0.27,0.75) {selected display burden};")
    println(io, "\\end{tikzpicture}")
    return String(take!(io))
end

function _expected_outputs()
    bridge = _parse_csv(BRIDGE_DATA)
    capacity = _parse_csv(CAPACITY_DATA)
    penalty = _parse_csv(PENALTY_DATA)
    return Dict(
        "bridge" => _bridge_source(bridge),
        "economic_geometry" => _economic_geometry_source(capacity, penalty),
    )
end

function generate_figure_audit_artifacts()
    expected = _expected_outputs()
    for key in sort!(collect(keys(OUTPUTS)))
        path = OUTPUTS[key]
        mkpath(dirname(path))
        write(path, expected[key])
    end
    return OUTPUTS
end

function check_figure_audit_artifacts()
    expected = _expected_outputs()
    for key in sort!(collect(keys(OUTPUTS)))
        path = OUTPUTS[key]
        isfile(path) || error("missing generated figure: $path")
        read(path, String) == expected[key] || error("generated figure drift: $path")
    end
    return OUTPUTS
end

function main()
    check_only = ARGS == ["--check"]
    isempty(ARGS) || check_only || throw(
        ArgumentError("usage: generate_figure_audit_artifacts.jl [--check]"),
    )
    outputs = check_only ? check_figure_audit_artifacts() :
              generate_figure_audit_artifacts()
    for key in sort!(collect(keys(outputs)))
        println(check_only ? "checked " : "wrote ", outputs[key])
    end
    return outputs
end

if abspath(PROGRAM_FILE) == @__FILE__
    main()
end

end
