#!/usr/bin/env python3
"""Reflow complete benchmark records without changing locked analysis outputs."""
import argparse
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TREE = ROOT / "journal/aor/online_resource"
# Fractions sum to one; column padding is subtracted by the TeX expression.
LAYOUTS = {
    "exact_method_agreement": [([0, 1, 2, 3, 4, 5, 6, 7], [.22, .12, .10, .12, .12, .12, .10, .10])],
    "registered_design_realized": [
        ([0, 1, 2, 3, 4], [.26, .18, .14, .23, .19]),
        ([0, 5, 6, 7, 8], [.26, .16, .20, .18, .20]),
    ],
    "computational_scaling": [
        ([0, 1, 2, 3, 4, 5, 6], [.13, .12, .25, .10, .10, .15, .15]),
        ([0, 1, 2, 7, 8, 9], [.13, .12, .25, .16, .16, .18]),
    ],
    "failure_statuses": [([0, 1, 2, 3, 4], [.14, .25, .28, .23, .10])],
    "registered_model_diagnostics": [([0, 1, 2, 3, 4, 5, 6], [.35, .12, .11, .10, .11, .11, .10])],
}


def wrap_cell(cell):
    # Permit breaks in long machine identifiers while retaining every character.
    if r"\_" in cell:
        raw = cell.replace(r"\_", "_")
        if re.fullmatch(r"[A-Za-z0-9_./-]+", raw):
            return r"\path{" + raw + "}"
    return cell


def render(stem, layouts):
    source = TREE / "tables" / (stem + ".tex")
    original = source.read_text()
    caption = re.search(r"\\caption\{(.*?)\}\\label\{(.*?)\}", original)
    assert caption, stem
    header = original.split("\\toprule\n", 1)[1].splitlines()[0].removesuffix(r" \\")
    headers = header.split(" & ")
    body = original.split("\\endhead\n", 1)[1].split("\\bottomrule", 1)[0]
    rows = [line.removesuffix(r" \\").split(" & ") for line in body.splitlines() if line.strip()]
    assert all(len(row) == len(headers) for row in rows), stem
    assert set(range(len(headers))) == {i for ids, _ in layouts for i in ids}, stem
    lines = ["% Generated by scripts/build_ssrn_tables.py; source rows are unchanged.",
             "% Source SHA-256: " + hashlib.sha256(source.read_bytes()).hexdigest()]
    for part, (indices, fractions) in enumerate(layouts, 1):
        assert abs(sum(fractions) - 1) < 1e-8
        alignment = "@{}" + "".join(
            r">{\raggedright\arraybackslash}p{\dimexpr " + f"{f:.3f}" +
            r"\linewidth-2\tabcolsep\relax}" for f in fractions
        ) + "@{}"
        part_caption = caption[1] + (f" Part {part} of {len(layouts)}; join by the repeated identifying columns." if len(layouts) > 1 else "")
        label = caption[2] + (f"-part-{part}" if part > 1 else "")
        head = " & ".join(headers[i] for i in indices) + r" \\"
        lines += [r"\begingroup", r"\small\setlength{\tabcolsep}{3pt}",
                  r"\setlength{\LTleft}{0pt}\setlength{\LTright}{0pt}",
                  r"\setlength{\LTcapwidth}{\linewidth}", r"\renewcommand{\arraystretch}{1.2}",
                  r"\begin{longtable}{" + alignment + "}",
                  r"\caption{" + part_caption + r"}\label{" + label + r"}\\",
                  r"\toprule", head, r"\midrule\endfirsthead",
                  r"\toprule", head, r"\midrule\endhead", r"\bottomrule\endfoot"]
        lines += [" & ".join(wrap_cell(row[i]) for i in indices) + r" \\" for row in rows]
        lines += [r"\end{longtable}", r"\endgroup"]
    return "\n".join(lines) + "\n", len(rows)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    out = TREE / "tables/readable"
    if not args.check:
        out.mkdir(parents=True, exist_ok=True)
    for stem, layouts in LAYOUTS.items():
        text, count = render(stem, layouts)
        target = out / (stem + ".tex")
        if args.check:
            assert target.read_text() == text, f"readable table drift: {stem}"
        else:
            target.write_text(text)
        print(f"{stem}: all {count} source rows and all columns retained")


if __name__ == "__main__":
    main()
