import Mathlib.Tactic
import StrategyInnovation.Value.SystemInteraction

/-!
# Primitive frontier--closure substitution

This module isolates an economically interpretable, recursion-stable
sufficient condition for T7 frontier--closure substitution.

The common descendant gap evolves under one fixed belief kernel shared by all
four frontier--closure corners.  Its high-frontier flow and terminal values are
pointwise below their low-frontier counterparts.  Nonnegative discounting and
the positive linear expectation operator preserve that order at every finite
horizon.  Rich-menu actions have nonnegative exposure to the resulting gap,
whereas every feasible poor-menu action has zero exposure.  The exposure
factorization therefore implies action-level relative saturation, and the
unchanged finite-max T7 theorem gives a nonpositive optimized cross difference.

The final section re-exports exact sign-boundary examples.  Project switching
and frontier-dependent candidate success produce complementarity outside the
primitive subclass; a separable surface has zero interaction.
-/

namespace StrategyInnovation

namespace Interaction

namespace PrimitiveSubstitution

open Projection
open Projection.Model
open Projection.Model.SystemInteraction

variable {model : FiniteModel}
variable {catalog : Raw.StrategyCatalog model}
variable {closure : Raw.ClosureOperator model}

/-! ## A fixed-kernel finite-horizon descendant gap -/

/--
Finite-horizon value of a descendant gap under a fixed transition kernel.

At horizon zero only the terminal gap is paid.  Each additional period adds
the current gap flow and the discounted expectation of the lower-horizon gap.
The same `transition` is used for the low- and high-frontier recursions below.
-/
def recursiveGapValue
    {Belief : Type*}
    (discount : ℚ)
    (transition : Belief → RatProb Belief)
    (flow terminal : Belief → ℚ) :
    Nat → Belief → ℚ
  | 0, belief => terminal belief
  | remaining + 1, belief =>
      flow belief +
        discount *
          (transition belief).expectation
            (recursiveGapValue discount transition flow terminal remaining)

/--
A fixed frontier-independent transition kernel preserves the descendant-gap
order through every finite-horizon recursion.

The proof uses only pointwise flow and terminal saturation, nonnegative
discounting, and nonnegative transition probabilities.  No optimizer appears
inside this recursion.
-/
theorem recursiveGapValue_antitone
    {Belief : Type*}
    (discount : ℚ)
    (transition : Belief → RatProb Belief)
    {flowLow flowHigh terminalLow terminalHigh : Belief → ℚ}
    (discount_nonnegative : 0 ≤ discount)
    (flow_antitone : ∀ belief, flowHigh belief ≤ flowLow belief)
    (terminal_antitone :
      ∀ belief, terminalHigh belief ≤ terminalLow belief) :
    ∀ horizon belief,
      recursiveGapValue discount transition flowHigh terminalHigh
          horizon belief ≤
        recursiveGapValue discount transition flowLow terminalLow
          horizon belief := by
  intro horizon
  induction horizon with
  | zero =>
      intro belief
      exact terminal_antitone belief
  | succ remaining inductionHypothesis =>
      intro belief
      simp only [recursiveGapValue]
      apply add_le_add (flow_antitone belief)
      apply mul_le_mul_of_nonneg_left
      · exact
          Projection.Model.UnifiedDecomposition.expectation_mono
            (transition belief) inductionHypothesis
      · exact discount_nonnegative

/--
Action-value decomposition whose common gap is generated by the process's
frontier-independent belief kernel.

The value equalities are the canonical fixed-continuation/single-descendant
restriction.  Costs, timing, operating adjustments, candidate laws, and the
continuation part outside the displayed gap are contained in the action
intercepts and common bases.  Unlike `CommonGapActionDecomposition`, the gap
order is not assumed at every horizon: it is derived from ordered primitive
flow and terminal gaps by `recursiveGapValue_antitone`.
-/
structure RecursiveCommonGapActionDecomposition
    (process : Model model catalog closure)
    (lowPoor lowRich highPoor highRich :
      CompressedLibraryState catalog closure) where
  flowLow : model.Belief → ℚ
  flowHigh : model.Belief → ℚ
  terminalLow : model.Belief → ℚ
  terminalHigh : model.Belief → ℚ
  flow_antitone :
    ∀ belief, flowHigh belief ≤ flowLow belief
  terminal_antitone :
    ∀ belief, terminalHigh belief ≤ terminalLow belief
  baseLow : Nat → model.Belief → ℚ
  baseHigh : Nat → model.Belief → ℚ
  richIntercept : Nat → model.Belief → Action model → ℚ
  poorIntercept : Nat → model.Belief → Action model → ℚ
  richExposure : Nat → model.Belief → Action model → ℚ
  poorExposure : Nat → model.Belief → Action model → ℚ
  richExposure_nonnegative :
    ∀ remaining belief action,
      0 ≤ richExposure remaining belief action
  poorExposure_zero :
    ∀ remaining belief action,
      ActionFeasible process (remaining + 1) lowPoor action →
        poorExposure remaining belief action = 0
  highRich_value :
    ∀ remaining belief action,
      nodeActionValue process remaining belief highRich action =
        baseHigh remaining belief +
          richIntercept remaining belief action +
            richExposure remaining belief action *
              recursiveGapValue process.discount process.beliefTransition
                flowHigh terminalHigh remaining belief
  highPoor_value :
    ∀ remaining belief action,
      nodeActionValue process remaining belief highPoor action =
        baseHigh remaining belief +
          poorIntercept remaining belief action +
            poorExposure remaining belief action *
              recursiveGapValue process.discount process.beliefTransition
                flowHigh terminalHigh remaining belief
  lowRich_value :
    ∀ remaining belief action,
      nodeActionValue process remaining belief lowRich action =
        baseLow remaining belief +
          richIntercept remaining belief action +
            richExposure remaining belief action *
              recursiveGapValue process.discount process.beliefTransition
                flowLow terminalLow remaining belief
  lowPoor_value :
    ∀ remaining belief action,
      nodeActionValue process remaining belief lowPoor action =
        baseLow remaining belief +
          poorIntercept remaining belief action +
            poorExposure remaining belief action *
              recursiveGapValue process.discount process.beliefTransition
                flowLow terminalLow remaining belief

/--
Finite-horizon recursion turns the transition-level certificate into the
common-gap action decomposition used by T7.
-/
def RecursiveCommonGapActionDecomposition.toCommonGap
    (process : Model model catalog closure)
    {lowPoor lowRich highPoor highRich :
      CompressedLibraryState catalog closure}
    (decomposition :
      RecursiveCommonGapActionDecomposition process
        lowPoor lowRich highPoor highRich) :
    CommonGapActionDecomposition process
      lowPoor lowRich highPoor highRich where
  baseLow := decomposition.baseLow
  baseHigh := decomposition.baseHigh
  gapLow :=
    recursiveGapValue process.discount process.beliefTransition
      decomposition.flowLow decomposition.terminalLow
  gapHigh :=
    recursiveGapValue process.discount process.beliefTransition
      decomposition.flowHigh decomposition.terminalHigh
  richIntercept := decomposition.richIntercept
  poorIntercept := decomposition.poorIntercept
  richExposure := decomposition.richExposure
  poorExposure := decomposition.poorExposure
  gap_antitone :=
    recursiveGapValue_antitone process.discount process.beliefTransition
      process.discount_nonnegative decomposition.flow_antitone
        decomposition.terminal_antitone
  richExposure_nonnegative := decomposition.richExposure_nonnegative
  poorExposure_zero := decomposition.poorExposure_zero
  highRich_value := decomposition.highRich_value
  highPoor_value := decomposition.highPoor_value
  lowRich_value := decomposition.lowRich_value
  lowPoor_value := decomposition.lowPoor_value

/--
The recursive primitive conditions imply action-level relative saturation.
-/
theorem recursive_primitives_imply_relativeActionSaturation
    (process : Model model catalog closure)
    {lowPoor lowRich highPoor highRich :
      CompressedLibraryState catalog closure}
    (decomposition :
      RecursiveCommonGapActionDecomposition process
        lowPoor lowRich highPoor highRich) :
    RelativeActionSaturation process
      lowPoor lowRich highPoor highRich :=
  relativeActionSaturation_of_commonGap process
    (decomposition.toCommonGap process)

/-! ## Adapter to the general finite-max theorem -/

/--
The canonical primitive subclass packages realizability, primitive frontier
independence, menu inclusion, and the recursion-generated common-gap
certificate.
-/
structure CanonicalPrimitiveSubstitutionAssumptions
    (process : Model model catalog closure)
    (lowPoor lowRich highPoor highRich :
      CompressedLibraryState catalog closure) where
  rectangle :
    FrontierClosureRectangle lowPoor lowRich highPoor highRich
  frontier_independent :
    Projection.Model.ComparativeStatics.FrontierIndependentPrimitives process
  opportunities_expand :
    process.available lowPoor ⊆ process.available lowRich
  recursiveCommonGap :
    RecursiveCommonGapActionDecomposition process
      lowPoor lowRich highPoor highRich

/-- The recursive primitive package supplies the existing T7 assumptions. -/
theorem CanonicalPrimitiveSubstitutionAssumptions.toSubstitutionAssumptions
    (process : Model model catalog closure)
    {lowPoor lowRich highPoor highRich :
      CompressedLibraryState catalog closure}
    (assumptions :
      CanonicalPrimitiveSubstitutionAssumptions process
        lowPoor lowRich highPoor highRich) :
    SubstitutionAssumptions process
      lowPoor lowRich highPoor highRich where
  rectangle := assumptions.rectangle
  frontier_independent := assumptions.frontier_independent
  opportunities_expand := assumptions.opportunities_expand
  relative_saturation :=
    recursive_primitives_imply_relativeActionSaturation process
      assumptions.recursiveCommonGap

/--
Relative action saturation implies that the finite-horizon optimized
frontier--closure cross difference is nonpositive.

This is the general finite-max comparison step, separated from the primitive
derivation above.
-/
theorem relative_saturation_implies_crossDifference_nonpositive
    (process : Model model catalog closure)
    {lowPoor lowRich highPoor highRich :
      CompressedLibraryState catalog closure}
    (rectangle :
      FrontierClosureRectangle lowPoor lowRich highPoor highRich)
    (frontier_independent :
      Projection.Model.ComparativeStatics.FrontierIndependentPrimitives process)
    (opportunities_expand :
      process.available lowPoor ⊆ process.available lowRich)
    (relative_saturation :
      RelativeActionSaturation process
        lowPoor lowRich highPoor highRich) :
    ∀ horizon belief,
      compressedInteractionCrossDifference process horizon belief
        lowPoor lowRich highPoor highRich ≤ 0 :=
  compressedInteractionCrossDifference_nonpositive process
    { rectangle
      frontier_independent
      opportunities_expand
      relative_saturation }

/--
Under the canonical recursion-stable primitive subclass, frontier and closure
are substitutes at every finite horizon and belief.
-/
theorem canonical_frontier_closure_substitutes
    (process : Model model catalog closure)
    {lowPoor lowRich highPoor highRich :
      CompressedLibraryState catalog closure}
    (assumptions :
      CanonicalPrimitiveSubstitutionAssumptions process
        lowPoor lowRich highPoor highRich) :
    ∀ horizon belief,
      compressedInteractionCrossDifference process horizon belief
        lowPoor lowRich highPoor highRich ≤ 0 :=
  compressedInteractionCrossDifference_nonpositive process
    (assumptions.toSubstitutionAssumptions process)

/-! ## Exact boundaries outside the primitive subclass -/

namespace Examples

open SystemInteraction.Examples

/--
Frontier-independent project switching can produce strict complementarity,
so the example cannot satisfy the primitive substitution subclass.
-/
theorem project_switching_complementarity_outside_primitive_subclass :
    interactionCrossDifference independentMenuSwitchValue 8 0
        richClosure poorClosure = 1 / 2 ∧
      ¬ AreSubstitutes independentMenuSwitchValue 8 0
        richClosure poorClosure := by
  constructor
  · exact independent_menu_switch_crossDifference_positive.2.2.1
  · intro substitutes
    unfold AreSubstitutes at substitutes
    rw [independent_menu_switch_crossDifference_positive.2.2.1] at substitutes
    norm_num at substitutes

/-- Frontier-dependent candidate success gives exact strict complementarity. -/
theorem frontier_dependent_success_complementarity_exact :
    interactionCrossDifference frontierDependentSuccessValue 1 0
        richClosure poorClosure = 1 / 2 ∧
      AreComplements frontierDependentSuccessValue 1 0
        richClosure poorClosure :=
  ⟨frontier_dependent_success_strict_complementarity.2.2.1,
    frontier_dependent_success_strict_complementarity.2.2.2⟩

/-- A nonconstant separable value surface has exactly zero interaction. -/
theorem separable_zero_interaction_exact :
    interactionCrossDifference separableValue 8 0
        richClosure poorClosure = 0 ∧
      AreSubstitutes separableValue 8 0 richClosure poorClosure ∧
      AreComplements separableValue 8 0 richClosure poorClosure :=
  ⟨separable_zero_interaction.2.2.1,
    separable_zero_interaction.2.2.2.1,
    separable_zero_interaction.2.2.2.2⟩

end Examples

end PrimitiveSubstitution

end Interaction

end StrategyInnovation
